### ISSUE TITLE
build fails under cygwin

### ISSUE THREAD

**Issue by johnmccash** [libyal/libewf#10]
Just tried to download and build current rev under cygwin. It fails with the following error:

```
make[2]: Entering directory '/cygdrive/c/Users/jm460/Downloads/libewf/libewf-master/libodraw'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcstring -I../libcerror -I../libcthreads -I../libcdata -I../libclocale -I../libcnotify -I../libcsplit -I../libuna -I../libcfile -I../libcpath -I../libbfio  -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64  -g -O2 -Wall -MT libodraw_cue_parser.lo -MD -MP -MF .deps/libodraw_cue_parser.Tpo -c -o libodraw_cue_parser.lo libodraw_cue_parser.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libcstring -I../libcerror -I../libcthreads -I../libcdata -I../libclocale -I../libcnotify -I../libcsplit -I../libuna -I../libcfile -I../libcpath -I../libbfio -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64 -g -O2 -Wall -MT libodraw_cue_parser.lo -MD -MP -MF .deps/libodraw_cue_parser.Tpo -c libodraw_cue_parser.c  -DDLL_EXPORT -DPIC -o .libs/libodraw_cue_parser.o
libodraw_cue_parser.c: In function 'cue_scanner_parse':
libodraw_cue_parser.c:1544:7: error: too few arguments to function 'cue_scanner_lex'
       yychar = yylex ();
       ^
libodraw_cue_parser.c:416:12: note: declared here
 extern int cue_scanner_lex(
            ^
libodraw_cue_parser.c:1658:30: error: 'parser_state' undeclared (first use in this function)
     ( (cue_parser_state_t *) parser_state )->error,
                              ^
libodraw_cue_parser.c:1658:30: note: each undeclared identifier is reported only once for each function it appears in
libodraw_cue_parser.c: In function 'cue_parser_parse_buffer':
libodraw_cue_parser.c:2742:8: error: too many arguments to function 'cue_scanner_parse'
        &parser_state ) == 0 )
        ^
libodraw_cue_parser.c:63:25: note: declared here
 #define yyparse         cue_scanner_parse
                         ^
libodraw_cue_parser.c:1388:1: note: in expansion of macro 'yyparse'
 yyparse (void)
 ^
Makefile:784: recipe for target 'libodraw_cue_parser.lo' failed
make[2]: *** [libodraw_cue_parser.lo] Error 1
make[2]: Leaving directory '/cygdrive/c/Users/jm460/Downloads/libewf/libewf-master/libodraw'
Makefile:697: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/cygdrive/c/Users/jm460/Downloads/libewf/libewf-master/libodraw'
Makefile:824: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Also, it would be really nice if there was an approved repository of precompiled downloads for Windows. Not everybody has windows compilers other than gnu, and the cygwin build has never worked as far as I'm aware.
Thanks
John

**Comment by hydrocloricacid** [comment]
I got it working with the git version by installing the mingw libraries (as well as following the build instructions for cygwin) and using the following command.

./configure --host=i686-w64-mingw32


If I didn't use the --host command it wouldn't build. (unable to make executables) (Was the first solution i found from google)

I had issues with the progress text as it updated all the time (or acq & verify) and didn't display the speed right (as below for verify). 
Will get a stable version and use that in future as JM recommends.


"Status: at 99%.
        verified 3.9 GiB (4227465216 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 0 second(s) with 23 bytes/second.

Status: at 99%.
        verified 3.9 GiB (4227661824 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 0 second(s) with 23 bytes/second.

Verify completed at: Feb 10, 2015 17:23:06

Read: 3.9 GiB (4227858432 bytes) in 18 second(s) with 23 bytes/second.

MD5 hash stored in file:                53df4eb51f2bc0298724b0763eae5bf8
MD5 hash calculated over data:          53df4eb51f2bc0298724b0763eae5bf8

ewfverify: SUCCESS
"

**Comment by hydrocloricacid** [comment]
oh and, that build method i mentioned above doesn't see the /dev/sda devices as it doesn't link against the cygwin libs. ( doesn't bother me)

you need to point to the windows devices instead.

e.g.
ewfacquire \\.\PhysicalDrive1

(remember to escape the slashes if using cygwin commandline)

**Comment by joachimmetz** [comment]
> I got it working with the git version by installing the mingw libraries (as well as following the build instructions for cygwin) and using the following command.

Bison support got added that is likely why it is working for you now.

> If I didn't use the --host command it wouldn't build. (unable to make executables) (Was the first solution i found from google)

Means configure cannot find the tools to build executables. Should work with cygwin without mingw as wel.

> oh and, that build method i mentioned above doesn't see the /dev/sda devices as it doesn't link against the cygwin libs. ( doesn't bother me)

So Cygwin is an odd case here since it is a hybrid between both systems, since Windows device paths are most native (closest to the system) I opted to use those and not go through the Cygwin abstraction layers.

**Comment by hydrocloricacid** [comment]
Re going direct.
Good decision, probably faster too

**Comment by joachimmetz** [comment]
Tested with commit: https://github.com/libyal/libewf/commit/751f2b3fecf23c23fcfd8d2ebcf9b7eaf29d8fe9 on latest Cygwin with byacc. `make` runs successful, closing issue.
