### ISSUE TITLE
[ewfacquire] Image size smaller than acquired disk. Free Space ignored?

### ISSUE THREAD

**Issue by klango** [libyal/libewf#102]
Hi guys, 
this may sound banal but I noticed when acquiring a 1TB HDD, I only got a 50GB Image, split in 20x 2.1GB files.
When analyzing the partitions in Hex, it does compute and detect around 800GB of free space in one partition.
How does ewfacquire deal with free space in disk? I thought it copies even the 0-byte values on disk into image, making a 1TB HDD into a 1TB Image (ignoring compression in this case).
 
Does the verify step shrinks it ignoring the free space bits?

Thanks!

#ewfacquire -V 
20160124

**Comment by joachimmetz** [comment]
did you use compression?
