### ISSUE TITLE
how to do with suspend and resume of acquisition now?

### ISSUE THREAD

**Issue by dijiang** [libyal/libewf#105]
as you mensioned on issue #7 add functionality to support user suspend and resume of acquisition , i need this functionality, is there any suggestion for me or how to realize it ?

**Comment by joachimmetz** [comment]
There is no functionality to suspend, there is only functionality to resume after a crash.

**Comment by joachimmetz** [comment]
> i need this functionality, is there any suggestion for me or how to realize it ?

implement it, or hire someone to implement it for you

**Comment by dijiang** [comment]
i am tring to implement it , based on your code , god bless me    ：）

**Comment by joachimmetz** [comment]
let's do a step back first then, where are planning to implement this? and how does this process going to look from a user perspective? Ctrl^C when running ewfaquire?

**Comment by dijiang** [comment]
my condition is that，i need to get raw image date from remote client . so the raw date is passed by net . when i get the raw date i use the lib to write in the format of ewf , somewhat like ewfaquirestream ( get the whole raw image then convert to ewf sometimes may be impossiable duo to the size of local disk ) ,  in the duration of passing date by net, user may suspend it or close the problem . so i need to support resume.
my plan is that, recored all the status by a config, and recover from the config to continue write ,and not write tail until true completed...

**Comment by joachimmetz** [comment]
In a separate tool or in ewfaquire? The quick and dirty way would be

* create an EWF image (or other temporary format) for every session and track that somewhere
* merge the sessions into a single EWF file when you have all the sessions

Not really suspend - resume but might give you the same functionality

For now the library does not provide you the interfaces to easily control the format for the suspend as you have it in mind. The resume currently also requires the full source disk

**Comment by dijiang** [comment]
thank you for your patience and suggestions...
for further,i need to study and think more

**Comment by joachimmetz** [comment]
ack, closing issue
