### ISSUE TITLE
issue building from source on siftv3

### ISSUE THREAD

**Issue by siftuser** [libyal/libewf#106]
I see that libbfio.h is present in /usr/local/include/libbfio.h

It's Ubuntu 18.04 w/ latest siftv3

But I still get following error installing libewf. Thanks!

In file included from libmfdata_file.h:29:0,
                 from libmfdata_file.c:27:
libmfdata_libbfio.h:49:2: error: #error Missing libbfio.h
 #error Missing libbfio.h
  ^~~~~
In file included from libmfdata_file.c:27:0:
libmfdata_file.h:102:6: error: unknown type name ‘libbfio_pool_t’
      libbfio_pool_t *file_io_pool,
      ^~~~~~~~~~~~~~
In file included from libmfdata_file.c:28:0:
libmfdata_file_list.h:71:9: error: unknown type name ‘libbfio_pool_t’
         libbfio_pool_t *file_io_pool,
         ^~~~~~~~~~~~~~
libmfdata_file_list.h:77:1: warning: no semicolon at end of struct or union
 };
 ^
libmfdata_file_list.h:92:13: error: unknown type name ‘libbfio_pool_t’
             libbfio_pool_t *file_io_pool,
             ^~~~~~~~~~~~~~
libmfdata_file_list.h:98:6: error: expected ‘;’, ‘,’ or ‘)’ before ‘uint8_t’
      uint8_t flags,
      ^~~~~~~
libmfdata_file_list.h:163:6: error: unknown type name ‘libbfio_pool_t’
      libbfio_pool_t *file_io_pool,
      ^~~~~~~~~~~~~~
libmfdata_file_list.h:173:6: error: unknown type name ‘libbfio_pool_t’
      libbfio_pool_t *file_io_pool,
      ^~~~~~~~~~~~~~
libmfdata_file.c:378:6: error: unknown type name ‘libbfio_pool_t’
      libbfio_pool_t *file_io_pool,
      ^~~~~~~~~~~~~~
Makefile:787: recipe for target 'libmfdata_file.lo' failed
make[1]: *** [libmfdata_file.lo] Error 1

**Comment by siftuser** [comment]
Thanks for responding! Yes I did ... after config, make fails w/ error as stated earlier

**Comment by joachimmetz** [comment]
Yes and these errors indicate you are missing dependencies and did not use a source package but pulled the code from git instead.

**Comment by siftuser** [comment]
Many thanks Joachim! config.log sent via dm.

**Comment by joachimmetz** [comment]
```
Building:
   libcstring support:                       local
   libcerror support:                        local
   libcthreads support:                      local
   libcdata support:                         local
   libcdatetime support:                     local
   libclocale support:                       local
   libcnotify support:                       local
   libcsplit support:                        local
   libuna support:                           local
   libcfile support:                         local
   libcpath support:                         local
   libbfio support:                          yes
   libfcache support:                        local
   libfdata support:                         local
   libfvalue support:                        local
   libmfdata support:                        local
   ADLER32 checksum support:                 zlib
   DEFLATE compression support:              zlib
   libhmac support:                          local
   MD5 support:                              libcrypto
   SHA1 support:                             libcrypto
   SHA256 support:                           libcrypto
   libcaes support:                          local
   AES support:                              libcrypto
   libodraw support:                         local
   libsmdev support:                         local
   libsmraw support:                         local
   libcsystem support:                       local
   GUID/UUID support:                        no
   FUSE support:                             libfuse
```

There appears to be a libbfio installed on the system that looks to be broken
```
   libbfio support:                          yes
```

Try to disable the libewf source from using the system provided libbfio:
```
./configure --with-libbfio=no
```

**Comment by siftuser** [comment]
Many thanks! that helped :)

**Comment by joachimmetz** [comment]
Ack, I'll close this issue then

**Comment by siftuser** [comment]
THANKS 👍
