### ISSUE TITLE
ewfmount help

### ISSUE THREAD

**Issue by klango** [libyal/libewf#113]
Hi Guys, 
I acquired an E01 image and wanted to mount it. I am not using mount_ewf.py but following the step by step:

ewf-tools Version
20140608-6
image: image.E01
I am the owner of the image

```
$ ll image.E01
-rw-r--r--  myuser myuser 85393 Oct 10 16:41 image.E01
```
mount on /tmp/ewf
```
$ ewfmount image.E01 /tmp/ewf
ewfmount 20140608
```
now I see the stream with root permissions
```
$ ll /tmp/ewf
-r--r--r--  1 root root 853622784 Okt 11 10:29 ewf1
```
So now I try to mount the stream on /tmp/ewf_mount/
```
$ sudo mount -o ro /tmp/ewf/ewf1 /tmp/ewf_mount/
mount: cannot mount /tmp/ewf/ewf1 read-only
```

i also tried with the -X flag:
```
$ ewfmount -X allow_root image.E01 /tmp/ewf
ewfmount 20140608

$ sudo mount -o ro /tmp/ewf/ewf1 /tmp/ewf_mount/
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
 missing codepage or helper program, or other error
```

also it does not work with fuse / nor fusermount

Any ideas?

**Comment by joachimmetz** [comment]
What is in the EWF file ? a disk image?

**Comment by klango** [comment]
> What is in the EWF file ? a disk image?

Yes which I also acquired with ewfacquire

**Comment by joachimmetz** [comment]
for a disk image you'll need to provide the offset of the volume that contains the file system

**Comment by klango** [comment]
Ok that could be the problem:
When checking the offset I found that the partition table is unknown:
$ parted image.E01
(parted) print                                                            
Error: /home/kk1/Andre/Vorgaenge/Nestler/Nestler_IDE_Festplatte.E01: unknown Partition table
Model:  (file)                                                           
Hard-drive  image.E01:  853938688B
Sektor size: 512B
Partition tablePartitionstabelle: unknown
Disk-Flags:

**Comment by klango** [comment]
@joachimmetz 
Testdisk sees the file system structure and all files  of the image.E01
I ended up using testdisk to rewrite the partition table for FAT16. 
Now I have the image.d01 file (created by testdisk) and the original .E01 image file. 
Do you know how to combine both or mount .E01 using .d01?

**Comment by joachimmetz** [comment]
Can you send me a hexdump of the first 4096 bytes of /tmp/ewf/ewf1

**Comment by klango** [comment]
hi @joachimmetz thank you for your prompt reply.
Yes I update this next week as soon as I get hold of the image again. 
Have a nice weekend°!

**Comment by joachimmetz** [comment]
No update in a while, closing issue.
