### ISSUE TITLE
win10 image mounting error using ewfmount on mac "Block device required"

### ISSUE THREAD

**Issue by siftuser** [libyal/libewf#116]
Trying to mount ntfs e01 image (created using ftkimager of a logical partition) on mac using ewfmount.  (libewf-experimental-20171104). ewfverify shows SUCCESS

e01 mount works 

```
ewfmount -X allow_other /Volumes/1T/Win.E01 /Users/user.name/mnt/fuse/
ewfmount@osxfuse0 on /Users/user.name/mnt/fuse (osxfuse, nodev, nosuid, synchronous, mounted by user.name)
```

However, while mounting NTFS partition throws error. Appreciate help :)

```
mount -t ntfs  -o rdonly,noexec,noowners /Users/user.name/mnt/fuse/ewf1 /Users/user.name/mnt/windows_mount
mount_ntfs: /Users/user.name/mnt/fuse/ewf1 on /Users/user.name/mnt/windows_mount: Block device required
```

**Comment by siftuser** [comment]
I did `git clone https://github.com/libyal/libewf-legacy.git`. Target folder does not contain any configure or makefiles ... 

 When I run ewfmount to check version, it shows 20171104

```
ewfmount -V
ewfmount 20171104
```
is this correct ? Thanks!

**Comment by joachimmetz** [comment]
> is this correct ?

this is not the legacy version, see: https://github.com/libyal/libewf-legacy/blob/master/configure.ac#L5

**Comment by siftuser** [comment]
Many thanks! Fair to assume it would support mounting ntfs e01 image (in chunks) on to a mac osx high sierra ? Thank you!

**Comment by joachimmetz** [comment]
Not sure what you mean?

The experimental version of libewf is "experimental". I do not recommend to use it for case related work, unless you're sufficiently familiar with the internals to troubleshoot issues. The "stable" (or legacy) version should work fine in exposing the content of an EWF image (set). 

Regarding NTFS support on MacOS that will likely depend on multiple factors.

**Comment by siftuser** [comment]
Apologies for not being clear. My question was, How do i install the stable version, as I don't see config, makefile in it. Is there atable version installer for mac ? Thanks much in advance!

**Comment by joachimmetz** [comment]
> as I don't see config, makefile in it.

This is explained here: https://github.com/libyal/libewf/wiki/Building#read-first

Get one of the packaged releases: https://github.com/libyal/libewf-legacy/releases and build from source using the same instructions as for the experimental version.

> Is there atable version installer for mac ?

There are no binaries or packaged version provided by the project maybe by MacPorts or Homebrew

**Comment by siftuser** [comment]
Thanks much @joachimmetz ! Sorry to bother, but the [releases page](https://github.com/libyal/libewf-legacy/releases) shows 20140804 as latest version & NOT [20140805](https://github.com/libyal/libewf-legacy/blob/master/configure.ac#L5) as suggested by you earlier. Thanks for your time in advance!

**Comment by joachimmetz** [comment]
20140805 is the latest version checked into git, when time permits I'll do a release

**Comment by siftuser** [comment]
Thanks! looking forward :)

**Comment by siftuser** [comment]
@joachimmetz just curious, any clue when would you be able to release 20140805 ? Thanks in advance!

**Comment by joachimmetz** [comment]
I'll have a look after the plaso release

**Comment by joachimmetz** [comment]
20140806 was released instead closing issue.
