### ISSUE TITLE
wide character support

### ISSUE THREAD

**Issue by sivid** [libyal/libewf#12]
Hello, I am sorry if it's not the correct place to ask questions but I couldn't find a place for discussion.  I compiled `libclocale` using these options:

    ./configure --enable-wide-character-type --enable-shared=no

and `libewf` using these options:

    ./configure --enable-verbose-output --enable-shared=no --enable-static-executables=yes --enable-python --enable-wide-character-type

````
Features:
   Multi-threading support:                  pthread
   Wide character type support:              yes
   ewftools are build as static executables: yes
   Python (pyewf) support:                   2.7
   Verbose output:                           yes
   Debug output:                             no
   Version 1 API compatibility:              no
````

Then I `ewfmount` a .E01 file, then `mount -o ro,loop` to mount it in Ubuntu 14.04.  I am seeing question marks like these in `ls`

    ????_2014 - 2015?????????????.docx 
where there should be CJK characters.  (Ubuntu itself can view CJK characters correctly)

So I guess my question is, are wide characters and Unicode supported?  If not, how can I correctly view those files?

**Comment by joachimmetz** [comment]
This has nothing to do with libewf. The wide character support applies to wchar_t function. Ubuntu 14.04 has UTF-8 support and does not require wchar_t support for Unicode. The wide char support will affect libewf functions only e.g. so you can pass it Unicode EWF image filename on Windows.

It looks more like the loopback mount driver is not returning you correct filenames. Which file system are you mounting?

Also check your locale settings `echo $LANG`

**Comment by sivid** [comment]
Thank you for your help, the filesystem is FAT32, I have checked on NTFS and it could properly see the characters, so the problem is probably not related to ewf, as you said.  I am closing the issue now, thanks again :)

**Comment by joachimmetz** [comment]
Have a look at: http://linux.die.net/man/8/mount try passing the codepage option when mounting the file system.
