### ISSUE TITLE
[PATCH] fix test_ewfacquire_device.sh and test_ewfacquire_resume.sh

### ISSUE THREAD

**Issue by rhash** [libyal/libewf#120]
Two tests test_ewfacquire_device.sh and test_ewfacquire_resume.sh still depends on the name of directory of libewf. This makes impossible to build a deb package with pbuilder or build from a renamed directory.

Here is the patch for current HEAD: [01-fix-two-ewfacquire-tests.patch.gz](https://github.com/libyal/libewf/files/2767392/01-fix-two-ewfacquire-tests.patch.gz)

Please apply the patch or fix these scripts.

The patch originates from debian libewf patches: https://salsa.debian.org/pkg-security-team/libewf/tree/debian/master/debian/patches

**Comment by joachimmetz** [comment]
@rhash please **do not** package and distribute the experimental version of libewf. I'd really wish that distro package maintainers would first check with project maintainers about the state of a project **before** packaging it for distribution.

 instead use the legacy https://github.com/libyal/libewf-legacy until the experimental version has reached alpha status

I'll have a look at the patches and changing the test when time permits.

**Comment by rhash** [comment]
@joachimmetz that's unexpected news :)

BTW, I've uploaded wrong patch, here is correct version:
[01-fix-two-ewfacquire-tests.patch_2.gz](https://github.com/libyal/libewf/files/2767525/01-fix-two-ewfacquire-tests.patch_2.gz)

**Comment by joachimmetz** [comment]
> @joachimmetz that's unexpected news :)

What is "unexpected news"? that this project is experimental or that distro package maintainers should talk more with project maintainers (at least from my perspective)?

**Comment by joachimmetz** [comment]
Changes similar to patches will be integrated in next commit
