### ISSUE TITLE
Building from source in macOS 10.13

### ISSUE THREAD

**Issue by gilcaroline** [libyal/libewf#123]
Hello,
I'm trying to build libewf <version 20171104> from source on a macOS High Sierra 10.13.6 machine

When trying to mount a E01, I'll get the "No sub system to mount EWF format."

I'm on FUSE for macOS 3.8.2. I've tried installing fuse-dev, but can't find a workable command. 
I suspect I am missing a configuration detail or that there is a compatibility issue between the version of libewf, my OS, xcode, and my version of FUSE. Could you please, help troubleshoot?

As a sidenote, I've been trying to find an alternative to the commands for the macOS universal binary on this page: https://github.com/libyal/libewf/wiki/Building#source-distribution-package. Are there any alternatives for Mac OS 10.13? The latest is 10.7

**Comment by joachimmetz** [comment]
what does config.log tell you about detecting the fuse for macos installation?

**Comment by gilcaroline** [comment]
Hi Joachim,

Many thanks for replying. I'm pasting below the fuse section of the config.log. 

CONFIGURE:57579: checking whether to use search for libfuse in includedir and libdir or in the specified DIR, or no if not to use libfuse
CONFIGURE:57607: checking for fuse
CONFIGURE:57614: $PKG_CONFIG --exists --print-errors "fuse >= 2.6"
CONFIGURE:57631: $PKG_CONFIG --exists --print-errors "fuse >= 2.6"
   FUSE support:                             libfuse
ac_cv_env_fuse_CFLAGS_set=
ac_cv_env_fuse_CFLAGS_value=
ac_cv_env_fuse_LIBS_set=
ac_cv_env_fuse_LIBS_value=
ac_cv_libfuse=libfuse
ac_cv_libfuse_CPPFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/opt/local/include/osxfuse/fuse'
ac_cv_libfuse_LIBADD='-L/opt/local/lib -losxfuse'
ac_cv_with_libfuse=auto-detect
pkg_cv_fuse_CFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/opt/local/include/osxfuse/fuse'
pkg_cv_fuse_LIBS='-L/opt/local/lib -losxfuse'
HAVE_LIBFUSE='1'
LIBFUSE_CPPFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/opt/local/include/osxfuse/fuse'
LIBFUSE_LIBADD='-L/opt/local/lib -losxfuse'
ax_libfuse_pc_libs_private='-lfuse'
ax_libfuse_spec_build_requires='fuse-devel'
ax_libfuse_spec_requires='fuse-libs'
fuse_CFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/opt/local/include/osxfuse/fuse'
fuse_LIBS='-L/opt/local/lib -losxfuse'
#define HAVE_LIBFUSE 1

**Comment by joachimmetz** [comment]
based on the config.log information `FUSE support: libfuse` libfuse is detected in /opt/local/lib.
Is this the location you expect it to be in (not the typical MacFUSE path if I recall correctly_? Or is there another libfuse installed on your system?

> As a sidenote, I've been trying to find an alternative to the commands for the macOS universal binary

Why would you need a macOS universal binary? Aren't most MacOS systems 64-bit little-endian only nowadays?

**Comment by gilcaroline** [comment]
Hi Joachim,
No, that it's not the location I was expecting to mount. Any way of changing that?
I had another libfuse installed in my system, which I deleted and now am back to the "no subsystem to mount EWF format." issue when trying to mount a ewf disk image using ewfmount. 

> Why would you need a macOS universal binary? Aren't most MacOS systems 64-bit little-endian only nowadays?
I wasn't sure if it was needed for my OS. I was following the instructions and thought I should ask.

Thank you,

**Comment by joachimmetz** [comment]
> No, that it's not the location I was expecting to mount. 

Technically that is the location of the libfuse library.

There are a couple of ways of solving configure detecting the wrong libfuse

(option A, clean up build environment)
1. look for all the locations of installations of libfuse on your installation:
`sudo find / -name \*fuse\*`
1. Remove all versions of fuse
1. Install FUSE for macOS
1. rerun configure
1. check if config log says `FUSE support: libosxfuse`

(option B point configure to the location of libosxfuse)
1. `./configure --with-fuse=/usr/local/lib` (where libfuse include and lib subdirs are in /usr/local/lib)

**Comment by gilcaroline** [comment]
Hi Joachim,

Thank you for walking me through this. I've just tried the option B, and am still getting the "No sub system to mount EWF format." error when trying to mount an e01. Any ideas?

**Comment by joachimmetz** [comment]
What does your config.log tell you?

**Comment by gilcaroline** [comment]
Hi Joachim,
This is the fuse section:

  $ ./configure --with-fuse=/Users/cgil/Downloads/libewf-20171104
configure:57579: checking whether to use search for libfuse in includedir and libdir or in the specified DIR, or no if not to use libfuse
configure:57607: checking for fuse
configure:57614: $PKG_CONFIG --exists --print-errors "fuse >= 2.6"
configure:57631: $PKG_CONFIG --exists --print-errors "fuse >= 2.6"
configure:61153: WARNING: unrecognized options: --with-fuse
   FUSE support:                             libfuse
ac_cv_env_fuse_CFLAGS_set=
ac_cv_env_fuse_CFLAGS_value=
ac_cv_env_fuse_LIBS_set=
ac_cv_env_fuse_LIBS_value=
ac_cv_libfuse=libfuse
ac_cv_libfuse_CPPFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse'
ac_cv_libfuse_LIBADD='-L/usr/local/lib -losxfuse'
ac_cv_with_libfuse=auto-detect
pkg_cv_fuse_CFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse'
pkg_cv_fuse_LIBS='-L/usr/local/lib -losxfuse'
HAVE_LIBFUSE='1'
LIBFUSE_CPPFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse'
LIBFUSE_LIBADD='-L/usr/local/lib -losxfuse'
ax_libfuse_pc_libs_private='-lfuse'
ax_libfuse_spec_build_requires='fuse-devel'
ax_libfuse_spec_requires='fuse-libs'
fuse_CFLAGS='-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/include/osxfuse/fuse'
fuse_LIBS='-L/usr/local/lib -losxfuse'
#define HAVE_LIBFUSE 1

**Comment by joachimmetz** [comment]
what is the exact (including paths) ewfmount command you are using?

**Comment by gilcaroline** [comment]
Hi Joachim,

Sorry for the delay, I'm a total novice!
I ran ./configure with the --with-libfuse flag. Still getting the 'No sub system to mount ewf format.
I either use: 'ewfmount -X allow_other /path/to/diskimage.E01 [mount point]' 
or this one which we found online and was the only command that would consistently work for use before we upgraded to High Sierra: 

'ewfmount -f ewf -X allow_other image.e01 ./mp; ln -s mp/ewf1 image.dmg; hdiutil attach -readonly image.dmg'

**Comment by gilcaroline** [comment]
Hello Joachim,
We did some more exploration on this issue. 
1. We uninstalled libewf and fuse and reinstalled using homebrew (osfxfuse first, then libewf). 
2.After that we followed your instructions up in the thread to clean up the build environment (option A). 
3. Following that, we got back to the 'No sub system to mount EWF format.' error.

Also, I think the config file output that I sent you before was referencing the wrong config file, since it's location is my download folder. But, I'm not too clear on that. Where would I find the libewf config file if I installed using homebrew?

Any thoughts and guidance would be appreciated!

**Comment by joachimmetz** [comment]
> No sub system to mount ewf format.

means that ewfmount was not build with fuse (or dokan) support, so `-X` does not help you there because there is no back-end to pass options to

> Where would I find the libewf config file if I installed using homebrew?

There would be none (to my knowledge) since brew provides a binary release. But if brew provides you with an ewfmount without libfuse support (which is maintained by the brew project) you'll need to build your own ewfmount (with libfuse) and run that version instead `./ewftools/ewfmount`

**Comment by gilcaroline** [comment]
Hi Joachim,

Thanks so much for walking us through this. To summarize, we want to be able to use and properly install libewf on our High Sierra 10.13 Mac workstations. I tried both building from source using the instructions on GitHub and installing libewf using homebrew. 

So far, we are only able to mount ewf images by "cd" to the libewf-20170703 directory I downloaded and calling the ewfmount command like so:  ./ewftools/ewfmount -X volicon=/Library/Filesystems/osxfuse.fs/Contents/Resources/Volume.icns  image.ewf fuse/

However, with that command the disk image shows up on the fuse mount volume as a 20GB text file. Based on a workaround suggested by a colleague, we are able to copy the disk image out of the fuse mount volume, add an .iso extension and properly mount some disk images.

Could you let us know why the disk image is showing up as a 20GB text file and, is there currently a more straightforward way to mount (and use libewf) on Mac High Sierra computers?

Thanks so much,

**Comment by joachimmetz** [comment]
@gilcaroline sry, must have missed your last update.

With "20GB text file" I presume you mean "the RAW storage media data contained in the EWF image" as described [here](https://github.com/libyal/libewf/wiki/Mounting#mounting)

If the EWF contains a disk image than on macOS this can be attached as a disk as any other RAW disk image:

```
hdiutil attach -imagekey diskimage-class=CRawDiskImage fuse/ewf1
```

Closing issue, question answered
