### ISSUE TITLE
Incorrect evaluation of parameter read_error_retries (-r)

### ISSUE THREAD

**Issue by michaeladler** [libyal/libewf#125]
I'm trying to invoke ewfacquire (version 20140608) with argument `-r 3` and I noticed the following output on stderr:

```
Unsupported number of error retries defaulting to: 128.
```

Since I'm using an older version of ewfacquire, I compared the code with the current version (master) and noticed something odd:

https://github.com/libyal/libewf/blob/33992fae384a9454990320228e8334be7bf709e1/ewftools/ewfacquire.c#L1934

Shouldn't this be `option_number_of_error_retries` instead of `option_sectors_per_chunk`? Grepping the code for `option_number_of_error_retries`, I realized that the variable's value is only ever read in an if-clause. This can't be right, can it?

**Comment by joachimmetz** [comment]
thx for the report, I'll have a look when time permits.

**Comment by joachimmetz** [comment]
Addressed in https://github.com/libyal/libewf/commit/eec75db5c624c42e8c6d2c092507ee6e2e30b47d
