### ISSUE TITLE
What's the status of this repo?

### ISSUE THREAD

**Issue by dc189** [libyal/libewf#126]
There are lots of commits in the master branch since the latest release in 2017, but it's not clear whether there are any important fixes, new features.

Should we use the current master branch (does it work, is it stable?) or the release?

**Comment by joachimmetz** [comment]
As the [README](https://github.com/libyal/libewf/blob/master/README) indicates this project is experimental. If you want a stable version of libewf us https://github.com/libyal/libewf-legacy

**Comment by dc189** [comment]
Yeah but I was wondering more what has changed between the 2017 release and the current master. Is there any notable improvements, features?

**Comment by joachimmetz** [comment]
With "2017 release" do you mean the pre-release on https://github.com/libyal/libewf/releases?

> Is there any notable improvements, features?

Why are you inquiring? As I said if you want to use this version of libewf for cases (production), use the legacy version. Unless you want to develop for libewf?

**Comment by dc189** [comment]
yes, 20171104. It seems to work fine for us so far.

Legacy doesn't support ex01 which we may need.

**Comment by joachimmetz** [comment]
that has not yet been completed and fully tested
