### ISSUE TITLE
ewftools needs -lsocket on Solaris

### ISSUE THREAD

**Issue by marksolaris** [libyal/libewf#134]
On Solaris 11 x86:

```
libtool: link: gcc -g -O2 -Wall -o .libs/ewfacquire byte_size_string.o digest_hash.o device_handle.o ewfacquire.o
    ewfinput.o ewftools_getopt.o ewftools_output.o ewftools_signal.o ewftools_system_string.o guid.o imaging_handle.o
    log_handle.o platform.o process_status.o storage_media_buffer.o storage_media_buffer_queue.o
    /usr/local/lib/libintl.so /usr/local/lib/libiconv.so  ../libodraw/.libs/libodraw.a ../libsmdev/.libs/libsmdev.a
    ../libsmraw/.libs/libsmraw.a -luuid ../libhmac/.libs/libhmac.a ../libfvalue/.libs/libfvalue.a ../libfguid/.libs/libfguid.a
    ../libfdata/.libs/libfdata.a ../libbfio/.libs/libbfio.a ../libcpath/.libs/libcpath.a ../libcfile/.libs/libcfile.a ../libuna/.libs/libuna.a
    ../libcsplit/.libs/libcsplit.a ../libcnotify/.libs/libcnotify.a ../libclocale/.libs/libclocale.a ../libcdatetime/.libs/libcdatetime.a
    ../libcdata/.libs/libcdata.a ../libewf/.libs/libewf.so -lcrypto ../libcthreads/.libs/libcthreads.a
    ../libcerror/.libs/libcerror.a -L/usr/local/lib -lc -lpthread -ldl -lbz2 -lz -R/usr/local/lib
Undefined                       first referenced
 symbol                             in file
socket                              /usr/local/lib/libuuid.a(gen_uuid.o)  (symbol belongs to implicit dependency /lib/libsocket.so.1)
connect                             /usr/local/lib/libuuid.a(gen_uuid.o)  (symbol belongs to implicit dependency /lib/libsocket.so.1)
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
gmake[1]: *** [ewfacquire] Error 1
gmake[1]: Leaving directory `libewf_2019_10_30/ewftools'
gmake: *** [all-recursive] Error 1
```

The fix is to include -l socket in the Makefile for that directory.

```
    ./configure --prefix=/usr/local
    perl -pe 's%-lz$%-lsocket -lz%' -i ewftools/Makefile
    gmake
```

**Comment by marksolaris** [comment]
These Issues are mostly posted here for the googlebot to find when people have problems with Solaris and setting up ewftools. It's posted as a fast and lazy solution, no action is required by you as I doubt Solaris is likely to be supported by the package ongoing. I'll post a binary of it to the Solaris Package Archive though.

The Solaris 11.3 is factory stock, so the same -lsocket issue will be seen again. I didn't want to pass the added -lsocket argument to the dozen or so libraries that synclibs.sh fetches, just the one that needed it.

Thanks!

**Comment by joachimmetz** [comment]
> I'll post a binary of it to the Solaris Package Archive though.

Please use https://github.com/libyal/libewf-legacy instead, this repo contains the experimental version of the library.

> The Solaris 11.3 is factory stock, so the same -lsocket issue will be seen again. 

Any indication why on Solaris libuuid needs libsocket and why it is in /usr/local instead of /usr?

**Comment by marksolaris** [comment]
>Please use https://github.com/libyal/libewf-legacy instead

Sure, I've got to redo the compile anyway to make a distributable libewf package, I'm working through satisfying the pre-reqs for testdisk(1) and logging Solaris specific stuff with the vendors as I find them. libewf was quite an elegant compile, just that one linking thing.

>Any indication why on Solaris libuuid needs libsocket and why it is in /usr/local instead of /usr?

libuuid doesn't ship with Solaris (checked via http://pkg.oracle.com/solaris/release/en/catalog.shtml). It would have been manually compiled by me for another tool, not sure which right at this minute as the Solaris host is elsewhere as I type. So it's a post-OS-install added library that the libewf configure located, and needs -lsocket when linked against.

**Comment by joachimmetz** [comment]
> libuuid doesn't ship with Solaris

I see, note that libuuid is only used by the ewftools to generate UUIDs when creating EWF files. So you could build without for testdisk purposes.

**Comment by marksolaris** [comment]
True, but I like the pain of satifying the full pre-reqs for things I compile :) Someone, somewhere will one day need this and if it's in the googlebot, they can keyword locate it.

**Comment by joachimmetz** [comment]
ack, closing issue.
