### ISSUE TITLE
What API should be used to get ExtendedAttribute values from a file entry when reading E0x/L0x files?

### ISSUE THREAD

**Issue by mikebbt** [libyal/libewf#135]
Attempting to read an L01 file and want to get the extended attributes for each of the file entries, which is the correct API call to do so?  I'm using libewf to access each file entry and get various information like DateAccessed, DateModified, FileIdent, Name etc.... the "libewf_file_entry_get_..." methods only have the call to get the root file entry extended attribute, other extended attribute calls seem to deal with single file (this may be it??) or simply "file_extended_attributes" which I believe is for creating the extended attributes to be added to an E0x/L0x file.  Any clarification would be appreciated, thanks.

**Comment by joachimmetz** [comment]
From which file system is the L01? any test data you can share?

**Comment by mikebbt** [comment]
The L01 is from HFS+ and I can create a sample to send you.

**Comment by joachimmetz** [comment]
yes please, I'm wondering what data is preserved in the L01 file regarding extended attributes.

**Comment by mikebbt** [comment]
[sample.L01.zip](https://github.com/libyal/libewf/files/3866017/sample.L01.zip)

**Comment by joachimmetz** [comment]
thx, I'm having a look tomorrow (local time)

**Comment by mikebbt** [comment]
Most appreciated, I was thinking the extended attributes were in the "ea" section of each file entry but not so sure, looking through the L01 w/hex editor to see if I can determine that.

**Comment by joachimmetz** [comment]
I think your hypothesis about the "ea" value could be correct.

```
libewf_single_files_parse_file_entry: type: mid with value: 84BEE4B5D37647FAAD1DC9A441B3510D.
libewf_single_files_parse_file_entry: type: ls with value: 1998848.
libewf_single_files_parse_file_entry: type: be with value: 1 0 1e8000.
libewf_single_files_parse_file_entry: type: id with value: 3.
libewf_single_files_parse_file_entry: type: cr with value: (null).
libewf_single_files_parse_file_entry: type: ac with value: (null).
libewf_single_files_parse_file_entry: type: wr with value: (null).
libewf_single_files_parse_file_entry: type: mo with value: (null).
libewf_single_files_parse_file_entry: type: dl with value: (null).
libewf_single_files_parse_file_entry: type: sig with value: (null).
libewf_single_files_parse_file_entry: type: ha with value: (null).
libewf_single_files_parse_file_entry: type: sha with value: (null).
libewf_single_files_parse_file_entry: type: snh with value: 1 .
libewf_single_files_parse_file_entry: type: p with value: (null).
libewf_single_files_parse_file_entry: type: n with value: $ExtentsFile.
libewf_single_files_parse_file_entry: type: du with value: (null).
libewf_single_files_parse_file_entry: type: lo with value: (null).
libewf_single_files_parse_file_entry: type: po with value: 0.
libewf_single_files_parse_file_entry: type: pm with value: 0.
libewf_single_files_parse_file_entry: type: oes with value: (null).
libewf_single_files_parse_file_entry: type: opr with value: 4194304.
libewf_single_files_parse_file_entry: type: src with value: 1.
libewf_single_files_parse_file_entry: type: sub with value: 1.
libewf_single_files_parse_file_entry: type: cid with value: (null).
libewf_single_files_parse_file_entry: type: jq with value: (null).
libewf_single_files_parse_file_entry: type: alt with value: (null).
libewf_single_files_parse_file_entry: type: ep with value: (null).
libewf_single_files_parse_file_entry: type: aq with value: (null).
libewf_single_files_parse_file_entry: type: cfi with value: (null).
libewf_single_files_parse_file_entry: type: sg with value: (null).
libewf_single_files_parse_file_entry: type: ea with value: 00000000010B0000000100000041007400740072006900620075007400650073000000000001000000000D0000000500000044006F004E006F007400500072006F00630065007300730000007400720075006500000001000000000700000005000000480069006400640065006E00000074007200750065000000.
libewf_single_files_parse_file_entry: type: lpt with value: (null).
```

```
00000000  00 00 00 00 01 0b 00 00  00 01 00 00 00 41 00 74  |.............A.t|
00000010  00 74 00 72 00 69 00 62  00 75 00 74 00 65 00 73  |.t.r.i.b.u.t.e.s|
00000020  00 00 00 00 00 01 00 00  00 00 0d 00 00 00 05 00  |................|
00000030  00 00 44 00 6f 00 4e 00  6f 00 74 00 50 00 72 00  |..D.o.N.o.t.P.r.|
00000040  6f 00 63 00 65 00 73 00  73 00 00 00 74 00 72 00  |o.c.e.s.s...t.r.|
00000050  75 00 65 00 00 00 01 00  00 00 00 07 00 00 00 05  |u.e.............|
00000060  00 00 00 48 00 69 00 64  00 64 00 65 00 6e 00 00  |...H.i.d.d.e.n..|
00000070  00 74 00 72 00 75 00 65  00 00 00                 |.t.r.u.e...|
0000007b
```

**Comment by joachimmetz** [comment]
This is currently not supported by libewf and would need some more format research to uncover all the details necessary to read this data.

**Comment by mikebbt** [comment]
Would it be possible to dump the contents of "ea" using libewf_file_entry_get_root_file_extended_attribute() as a starting point?

**Comment by joachimmetz** [comment]
@mikebbt not sure what you are asking there is no API function named `libewf_file_entry_get_root_file_extended_attribute`

* if you are asking if an API function can be added to expose the extended attribute data, the answer is:
** it is open source you can always add what you need under the license
** it will take time to add such a function, tests, analyze edge cases, etc. and my time is limited at the moment.

**Comment by mikebbt** [comment]
Apologies, my version has changes to the API (Pull Request #132 Changes for Reading LEF Files) that have added this function, will continue to work with that.  I had thought that these changes were in the main repo, closing this enquiry.

**Comment by joachimmetz** [comment]
> my version has changes to the API (Pull Request #132 Changes for Reading LEF Files) that have added this function, will continue to work with that

This will likely take a while before I merge them, mainly due to available time
