### ISSUE TITLE
Are Source and Subject Categories in L01's ltree mandatory for libewf to read file entry

### ISSUE THREAD

**Issue by mikebbt** [libyal/libewf#138]
This a general question on some behavior I noticed when reading L01's w/libewf.  If I export an L01 that doesn't include Source or Subject Category (no headers for these in ltree) and import this L01 using latest libewf (20200216 or 20200201) to read the file entry I get an error (root file entry error - single files missing).  Are the Source and Subject Categories mandatory when writing to an L01?  I haven't found anything that mentions this, I've noticed that initializing these structures (even if they are not used) seems to create the headers in the L01 ltree and those L01's can be read by libewf w/o issue.  Running w/the slightly older libewf (20190105) seems to not care about these items being in the ltree or not.  Wondering if this is a bug or maybe these items are now required?

Thanks

**Comment by joachimmetz** [comment]
* could you provide me the debug output of the first part of the ltree section (the first 2 levels)
* what is the full error?

**Comment by mikebbt** [comment]
The full error is below, will pass along additional libewf debug when I can get it.

libewf_handle_get_root_file_entry: invalid handle - missing single files.

**Comment by joachimmetz** [comment]
ACK

> Are the Source and Subject Categories mandatory when writing to an L01? 

It's a part of the format that was never officially documented, so I can only tell based on observations. I might not have such a case in my test data. Debug format output could be beneficial here for creating a test case. 

I'll have a look if the code now is more strict about this (likely will add a test case), as soon as time permits.

**Comment by joachimmetz** [comment]
Various changes were made to L01, however L01 does not seem to be compatible between various other tools, hence I assume L01 is no longer a single format. I'll need test files to add support for more exotic L01 files.
