### ISSUE TITLE
Dependencies mentioned in build instructions do not correspond with those in dpkg/control

### ISSUE THREAD

**Issue by mivtdole** [libyal/libewf#139]
The "python3-setuptools" package is missing as a dependency in the build wiki when trying to build Debian packages.

**Comment by joachimmetz** [comment]
Which version of Debian?

**Comment by joachimmetz** [comment]
Are you trying to tell me that dpkg/control has a build requirement on python3-setuptools and this is not mentioned in the build instructions?

**Comment by joachimmetz** [comment]
Wiki updated.
