### ISSUE TITLE
Compression on the fly?

### ISSUE THREAD

**Issue by klango** [libyal/libewf#141]
Does the compression run on the fly when imaging a drive?

**Comment by joachimmetz** [comment]
@klango what do you mean with "compression running on the fly" ?

**Comment by klango** [comment]
> @klango what do you mean with "compression running on the fly" ?

whether the data compression on the image is done as the image is acquired, or after the acquiring process.

**Comment by joachimmetz** [comment]
both the ewftools and libewf can compressed the source (image) data during the acquisition process

**Comment by klango** [comment]
Thanks for the prompt response @joachimmetz
