### ISSUE TITLE
Update for cygwin build guide

### ISSUE THREAD

**Issue by JustMyGithub** [libyal/libewf#144]
I builded on cygwin today I noticed that the documentation is not fully correct (anymore?)

bzip2-devel seems to be called libbz2-devel
gettext-devel is needed, not gettext
gcc-g++ is needed, not gcc-core

I tested with current checkout, not with the 2017 source distribution package -don't know whether this makes any difference. I hope this helps others

**Comment by joachimmetz** [comment]
It is likely that `gcc-g++` depends on `gcc-core` and therefore installs it. `gcc-g++` is currently mainly needed to satisfy the `./configure` check (unless if you're planning to build the ossfuzz fuzz targets). 

Regarding `gettext`, technically autopoint is needed. This was in `gettext-devel` previously. I'll need to check if that it was moved to `gettext-autopoint`

Regarding `bzip2-devel` I'll have a look, this dependency is not really used yet in the experimental version.

**Comment by joachimmetz** [comment]
wiki pages updated https://github.com/libyal/libewf/wiki/Building#cygwin
