### ISSUE TITLE
Limitation on source size?

### ISSUE THREAD

**Issue by finoradin** [libyal/libewf#147]
I am trying to use `ewfacquire` to image a 14TB (14999997644800 bytes) array, and when I use `ewf` format it tells me that the number of segments will exceed the maximum value:

```
Unnable to acquire input.
libewf_write_io_handle_initialize_values: the maximum number of allowed segment files will be exceeded with the segment file size: 1572864000.
libewf_handle_write_buffer: unable to initialize write IO handle values.
imaging_handle_write_buffer: unable to write storage media buffer.
ewfacquire_read_input: unable to write data to file.
ewfacquire: FAILURE
```

I actually don't even want to segment my output file at all… but I don't see that as an option. I instead try encase6 output as I see it has a higher segmenet size, but this still fails:

```
Unable to acquire input.
libmfdata_array_resize: invalid entries size value exceeds maximum.
libmfdata_list_resize: unable to resize elements array.
libewf_write_io_handle_write_new_chunk: unable to resize chunk table.
libewf_handle_write_buffer: unable to write new chunk.
imaging_handle_write_buffer: unable to write storage media buffer.
ewfacquire_read_input: unable to write data to file.
Unable to close output file(s).
libmfdata_array_resize: invalid entries size value exceeds maximum.
libmfdata_list_resize: unable to resize elements array.
libewf_write_io_handle_write_new_chunk: unable to resize chunk table.
libewf_handle_write_finalize: unable to write new chunk.
libewf_handle_close: unable to finalize write.
imaging_handle_close: unable to close output handle.
```

**Comment by joachimmetz** [comment]
> I actually don't even want to segment my output file at all… but I don't see that as an option. 

Just set it to the maximum

>  instead try encase6 output as I see it has a higher segmenet size, but this still fails:

Which version of libewf did you use? Could you be running into https://github.com/libyal/libewf-legacy/issues/9

**Comment by finoradin** [comment]
> Which version of libewf did you use? Could you be running into [libyal/libewf-legacy#9](https://github.com/libyal/libewf-legacy/issues/9) ?

Whatever is in Homebrew - freshly installed yesterday. Do you recommend building from source instead?

**Comment by joachimmetz** [comment]
> Whatever is in Homebrew 

this project is not directly involved with Homebrew so I have no idea what version that is

> Do you recommend building from source instead?

Depends how comfortable/experienced you are with that? I current don't have the bandwidth to help troubleshoot issues related to setting up a build environment.

**Comment by finoradin** [comment]
Ok looks like I'm running 20140811… 

I'm not passing it any chunking or segmenting options – could that be part of the issue?

**Comment by joachimmetz** [comment]
> I'm not passing it any chunking or segmenting options – could that be part of the issue?

yes, that means you are using the defaults.

**Comment by joachimmetz** [comment]
no further follow up question reporter, assuming question has been answered
