### ISSUE TITLE
Wrong function call

### ISSUE THREAD

**Issue by 286DX** [libyal/libewf#149]
https://github.com/libyal/libewf/blob/d4c49e3d558251741f517f1d8ca170c0c350a863/libewf/libewf_handle.c#L14989

There must be libcthreads_read_write_lock_release_for_write instead.

**Comment by joachimmetz** [comment]
thx for the report I'll have a look when time permits

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libewf/commit/11cf36b6d9e81ff96d22ae8e9d805eb15c2bd423
