### ISSUE TITLE
download's link not working

### ISSUE THREAD

**Issue by hydrocloricacid** [libyal/libewf#15]
Could you please update the downloads link ?

The download link on the building page "https://github.com/libyal/libewf/wiki/Building" doesn't work.
Would like to download and build a stable copy.

Cheers.

**Comment by joachimmetz** [comment]
The link works for me should point to a Google drive page.

**Comment by hydrocloricacid** [comment]
Odd.Just tried on my phone and the link works fine.was using Firefox at
work and it didn't work.
Ok thanks for checking that.
