### ISSUE TITLE
Permission denied when running setup.py

### ISSUE THREAD

**Issue by DeakinO** [libyal/libewf#154]
I've been following the instructions provided in the building documentation and when I try to run the install command I get the following error:

[Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-22600.write-test'

It looks like the issue is in the file path that the installer is trying to access, or there's an issue with running the command. I know the command needs to be run as an administrator, but when I've tried to do this it's encountered the same issue.

I know I could just be following the building documentation incorrectly, so any help on where it might be going wrong would be appreciated.

**Comment by joachimmetz** [comment]
This is a permission issue on your build system.

**Comment by DeakinO** [comment]
The file path that it states that it's trying to access is this one:

![Error_capture](https://user-images.githubusercontent.com/84642419/119261779-c9e8c900-bbd0-11eb-8ee8-0bff0f21890e.PNG)

Should the file path it is trying to follow contain the \\ as it's obviously never going to find these locations?

**Comment by joachimmetz** [comment]
> Should the file path it is trying to follow contain the \ as it's obviously never going to find these locations?

Not sure what you are asking, but **no where** in the setup.py of libewf is this path specified.

Again, this is an artifact of **your build system**, somewhere in **your local configuration** (I presume of easy install) this path is invoked.

**Comment by DeakinO** [comment]
Sorry, I thought I put double \, it's shown in the image attached.

I understand that the issue is likely with my system, I don't suppose you have any help that could fix the issue? It's okay if not, I've just look at as many resources as possible online and nothing I've tried has seemed to fix the issue.

**Comment by joachimmetz** [comment]
> I don't suppose you have any help that could fix the issue?

How? I have no idea how your system is configured. I don't have a crystal ball that tells me what is wrong and your problem description lacks the necessary details.

> I understand that the issue is likely with my system, I don't suppose you have any help that could fix the issue? It's okay if not, I've just look at as many resources as possible online and nothing I've tried has seemed to fix the issue.

However if I websearch for "test-easy-install-22600.write-test" (literally a 1 sec search) I find https://stackoverflow.com/questions/3995339/python-easy-install-gives-errno13 which indicates to me that you are trying to install into a location without the necessary permission (access rights to do so).
