### ISSUE TITLE
write access currently not supported - compiled without zlib

### ISSUE THREAD

**Issue by pipizhao-2020** [libyal/libewf#157]
I don't know why this error: write access currently not supported - compiled without zlib appears. is there a problem with zlib?

**Comment by joachimmetz** [comment]
This means you did not compile the source with zlib, which it needs to support writing EWF files.

**Comment by pipizhao-2020** [comment]
but i have compiled the ewfacquire with zlib.lib

**Comment by joachimmetz** [comment]
@pipizhao-2020 can you then be more specific about what steps you took, build details, platform, etc.
I cannot help you if you don't provide the necessary information to do so.

**Comment by pipizhao-2020** [comment]
I build the ewfacuqire with the Additional dependencies below:
libbfio.lib
libcaes.lib
libcdata.lib
libcdatetime.lib
libcerror.lib
libcfile.lib
libclocale.lib
libcnotify.lib
libcpath.lib
libcsplit.lib
libcthreads.lib
libfcache.lib
libfdata.lib
libfdatetime.lib
libfguid.lib
libfvalue.lib
libhmac.lib
libodraw.lib
libsmdev.lib
libsmraw.lib
libuna.lib
libewf.lib
bzip2.lib
zlib.lib
rpcrt4.lib
in visual studio 2017 in windows

**Comment by joachimmetz** [comment]
> I build the ewfacquire in visual studio 2017 in windows

Which version? directly from the git source or one of the experimental pre-releases ? https://github.com/libyal/libewf/releases

**Comment by pipizhao-2020** [comment]
I use the command: git clone https://github.com/libyal/libewf.git  to download the code , This should be the latest version.

**Comment by joachimmetz** [comment]
So that is the development version of the experimental version of libewf, which unless you're developing or testing libewf I not recommend using. Use this version https://github.com/libyal/libewf-legacy instead for "production purposes"

Regarding the issue you might be missing `HAVE_WRITE_SUPPORT` in the build process try adding it to https://github.com/libyal/libewf/blob/main/common/config_winapi.h

**Comment by pipizhao-2020** [comment]
I want to use it for development,I should know how to create E01 file and parse E01 file. Do you have E01 relevant information or some related principles? i have try adding it to config_winapi.h and it works. but it create a lot of files like test.E01、test.E02、test.E03 and so on. is that normal? i just want to save the hardDisk data in one file like test.E01. thank you very much for your answer.

**Comment by joachimmetz** [comment]
> I want to use it for development,I should know how to create E01 file and parse E01 file. 

if that means you're not developing libewf itself, use the legacy version

> but it create a lot of files like test.E01、test.E02、test.E03 and so on. is that normal?

yes

> i just want to save the hardDisk data in one file like test.E01

change the format setting before writing the data

**Comment by pipizhao-2020** [comment]
thank you for your answers, i should read your code in detail now.

**Comment by joachimmetz** [comment]
> i should read your code in detail now.

start with the include header include/libewf.h and format documentation https://github.com/libyal/libewf/tree/main/documentation that should give you an idea abut the settings/features

**Comment by joachimmetz** [comment]
Question seems to have been answered, closing issue
