### ISSUE TITLE
Status information updating too often under Windows

### ISSUE THREAD

**Issue by hydrocloricacid** [libyal/libewf#16]
###environment
Source code version : libewf-20140608.tar.gz
(have also tried with latest from git (cloned yesterday))
OS: windows 7 64 bit

built under cygwin using following configure command (as well as usual make and make install)
./configure --host=i686-w64-mingw32 --enable-static-executables --enable-python

ewfacquire \\.\PhysicalDrive1
Worked fine but with similar issues with status updating too soon.

These tools work perfectly fine apart from the status update which spams the screen with updates as well as the transfer rate being incorrect.

misc note:
1. the status update oddly affects performance more under cmd.exe as compared to when being run under cygwin terminal
2. didn't have python dev files install so enable python was ignored. (as per .configure output)

### Issue
Status information is updating too often. (example below)
Affects the performance as well as the transfer rate seems affected.

< begin snip>
Status: at 20%.
        verified 829 MiB (869826560 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 829 MiB (869924864 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 829 MiB (870055936 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 829 MiB (870154240 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 829 MiB (870252544 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 829 MiB (870285312 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 830 MiB (870416384 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 830 MiB (870547456 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 830 MiB (870711296 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

Status: at 20%.
        verified 830 MiB (870875136 bytes) of total 3.9 GiB (4227858432 bytes).
        completion in 33 second(s) with 10 bytes/second.

**Comment by joachimmetz** [comment]
I'll have a look to see if I can reproduce this when time permits.

**Comment by hydrocloricacid** [comment]
no prob's. whenever convenient

**Comment by hydrocloricacid** [comment]
Alternatively, adding an runtime option so that the status only updates on every 1% change would resolve this issue. (will bypass the problem)

I think I can remember this being the behaviour of the older version of ewfacquire.

I have looked at the process_status.c and the ewfacquire.c file but couldn't figure out where the code was which calls the status update for "every so often" as compared to "if new percentage". Will look at it again when I get time. Would look at disabling the "every so often" status update and keeping the "if new percentage" (e.g. -Q keeps the percentage updates ... etc).

**Comment by joachimmetz** [comment]
Bug reproduced. It is an issue in libcdatetime fix pending, closing issue.
