### ISSUE TITLE
How analyze the content of E01?

### ISSUE THREAD

**Issue by pipizhao-2020** [libyal/libewf#161]
i want to analysis the file information that contains in the E01 file.

**Comment by joachimmetz** [comment]
The content of an E01 depends on what you put into it. If it is a hard disk you need to analyze it with tooling that understand partition tables, volume systems and files systems. If it is process memory, you need tooling that can help debug/analyze process memory.

**Comment by pipizhao-2020** [comment]
is a hard disk，i want to analyze it by myself with c/c++.

**Comment by joachimmetz** [comment]
Then you need to write the tooling to analyze it. Start doing research on different partition tables, volume system and files system format. Maybe there is existing tooling out there you can use. This is out of scope for this project, I'll consider this question answered and close this issue.
