### ISSUE TITLE
How do I use/enable wide character support ?

### ISSUE THREAD

**Issue by mikebbt** [libyal/libewf#166]
I have modified my build script to include `--enable-wide-character-type=yes` when running configure (Windows builds only).  When I run my app it doesn't look like the wide calls are being made.  Is there something else that I need to do (other dependencies, additional configure args etc...) to get wide character working?

**Comment by joachimmetz** [comment]
@mikebbt can you provide more detail about

* an outline of what you're trying to accomplish
* your build environment (mingw? visual studio?)
* issues you're running into / what is "not working" ?

**Comment by mikebbt** [comment]
When writing or reading an L01 from our app the path/filename may contain Unicode characters (Russian, Chinese are most prevalent).  The build environment cross-compiles libewf for Windows from a Mac, I'm not the custodian so can try to find more detail from the devops team if needed.  So I have modified their build script as I have mentioned above to simply add the wide character enable flag.  The library builds fine, when the app is run I'm calling libewf_handle_open_wide(), the issue occurs on the closure:

Error is 'libewf_handle_write_finalize: unable to write finalize. [libcfile_file_open_with_error_code: unable to open file: <my file path here> with error: The filename, directory name, or volume label syntax is incorrect.]'.

Added some prints in the libewf code and checked to see if `HAVE_WIDE_SYSTEM_CHARACTER` was defined and it's not so I've missed something on the build side I'm assuming.

**Comment by joachimmetz** [comment]
First of all L01 is a proprietary format.

Which paths? Those in the the L01 or those of the local file system?

**Comment by mikebbt** [comment]
Understood we are using libewf as part of our proprietary exporting.  The paths for the local file system is what I'm dealing with, a simple path on a Windows machine.  My test case has the destination directory in Russian.

**Comment by joachimmetz** [comment]
> My test case has the destination directory in Russian.

so windows has a `char` (or ansi) and `wchar_t` (or unicode) file system methods (most other platforms have Unicode `char` support). `--enable-wide-character-type=yes` enables these `wchar_t` methods so you calling application can use the `_wide` functions. You'll need to pass them native Unicode encoded paths, which on Windows is UTF-16.

`--enable-wide-character-type=yes` should do the trick for build systems that use the configure script. For visual studio you have to make the necessary configuration changes

**Comment by mikebbt** [comment]
Thanks for the confirmation, will go back and review how libewf is being built as the issue must be there somewhere.

**Comment by mikebbt** [comment]
Finally did get this working, needed to change a #ifdef in types.h.in:

FROM:
#if defined( WINAPI ) && ( defined( _UNICODE ) || defined( UNICODE ) )

TO:
#if defined ( WINAPI )

I couldn't see anywhere that UNICODE was defined so tweaked it for now, in my case always having wide char suppoort for Windows is what we want.

**Comment by mikebbt** [comment]
My question was asking if passing "enable for wide char" to the config would allow me support, it didn't.  I assumed (maybe wrongly) that setting that would have defined HAVE_WIDE_SYSTEM_CHARACTER in the code but it didn't without this tweak to types.h.in.  Was there something else I could have done in the build stage to accomplish the same thing?

**Comment by joachimmetz** [comment]
> Was there something else I could have done in the build stage to accomplish the same thing?

I don't know you have not provided me sufficient information to answer this question:

* what is your build environment?
* how are you using libewf, as a DLL?
* what functions are you calling? what path are you passing to them?

**Comment by mikebbt** [comment]
Build env: cross-compile of libewf for Windows on MacOS using mingw

Usage: libewf is built as a dll

Functions called to read:
- libewf_glob_wide
- libewf_handle_initialize
- libewf_handle_set_maximum_number_of_open_handles
- libewf_handle_open_wide
- libewf_glob_wide_free
- use handle to read in e01 and process, then close

Path: "C:\Users\user-test\еуыеД01\files.e01"

**Comment by joachimmetz** [comment]
Has `--enable-winapi` has been provided to configure as well?

**Comment by mikebbt** [comment]
Checked the build script and I don't see `--enable-winapi`, will investigate the path and look into the codepage calls.
