### ISSUE TITLE
options questions about the write in pyewf

### ISSUE THREAD

**Issue by Octsec** [libyal/libewf#167]
Hi, Thanks for the answer to the previous question. i solved that problem. 
I have a few questions while using the pyewf library. 

When I create a 256GB size EWF file, can I change the extension name to ex01 not e01?
and i knew encase create segments file size more than that 200GB.. but using pyewf create ewf files , segements file 1.4 gb.
Can I increase the file size more that 1.4gb using pyewf?

**Comment by joachimmetz** [comment]
not at the moment, I've created https://github.com/libyal/libewf/issues/171

**Comment by Jaykitkukadiya** [comment]
can you please share proper procedure for creating e01 file using python script. i am wondering now.
