### ISSUE TITLE
ewfacquire "resume" reimages source file

### ISSUE THREAD

**Issue by Se11eR** [libyal/libewf#17]
When trying to reproduce steps from test_ewfacquire_resume.sh I noticed that source file is re-acquired from the beggining (the "status" messages start from 0%) when ewfacquire is called with -R flag. Also ewfacquire determines "Resume acquiry offset" from "underimaged" file as 0, which also seems weird to me, however confirms strange behaviour. This behaviour seems more like "restart" but not "resume".

Also when using .NET bindings, library behaves the same way:
1. I open handle, set media size to, say, 1GB.
2. Write half of the size, close the handle.
3. Reopen it with "WriteResume" access flags.
4. Try to write the remaining half (seeking to the 500MB), but witness that it writes form the beginning of the file, overwriting previously written data, as if no seeking was performed.

* Affected by versions: 20150126 (from the repo), 20140608 (from [downloads](https://53efc0a7187d0baa489ee347026b8278fe4020f6.googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/))
* Build from MSVS 2013. However "./configure", "make", "make dist" were made on CentOS, then I moved files to Windows machine.
OS: Windows 8 64 bit.

**Comment by joachimmetz** [comment]
Being able to resume EWF files is highly dependent on several criteria. It will need to resume:

* it is intended to re-start when the system or source disk powers does unexpectedly, so not a I write 500M now and 500M later type of resume
* it can only resume after the last reliable "chunk group", in your tests in which section does the data gets truncated?

**Comment by Se11eR** [comment]
* I am trying to achieve "pause" behaviour when I set media size to the intended maximum size, stop acquiry at some point and then resume it to the end. Is it possible?
* In the "sectors" section. In .NET bindings attempts I actually close the handle. However the file remains with "sectors" section being last and not filled to end.

**Comment by joachimmetz** [comment]
> I am trying to achieve "pause" behaviour when I set media size to the intended maximum size, stop acquiry at some point and then resume it to the end. Is it possible?

What's the point of doing this? This will only raise the possibilty of something going wrong.

> In the "sectors" section. In .NET bindings attempts I actually close the handle. However the file remains with "sectors" section being last and not filled to end.

Not sure what you mean, the file will be closed, but the missing data is not padded to the file. Why would you want that behavior? Either way your image is broken.

**Comment by Se11eR** [comment]
* It's a part of functionality of the software I am trying to adapt libewf to: being able to pause imaging. Pretty useful, actually.
* "in which section does the data gets truncated?": In EWF "sectors" section. And yes, image is broken. Any ideas how to avoid this?

**Comment by joachimmetz** [comment]
> It's a part of functionality of the software I am trying to adapt libewf to: being able to pause imaging. Pretty useful, actually.

I see several challenges with this approach that make me think these outweigh the usefulness of the feature:

* the source media can change in-between imaging
* you'll need to recalculate the integrity hashes, which will fail if the source media has changed
* a disk can refuse to start after each power cycle

> Any ideas how to avoid this?

You can try pausing your program at runtime without closing the EWF file.
