### ISSUE TITLE
libcthreads_read_write_lock_release_for_write overwriting result in libewf_internal_handle_open_file_io_pool 

### ISSUE THREAD

**Issue by taco-paco** [libyal/libewf#170]
[Errors from libewf_internal_handle_open_file_io_pool](https://github.com/libyal/libewf/blob/fc1ed7b7bd83a6a65dcc3bf38d7f696735734d7a/libewf/libewf_handle.c#L1172) get overwritten [here](https://github.com/libyal/libewf/blob/fc1ed7b7bd83a6a65dcc3bf38d7f696735734d7a/libewf/libewf_handle.c#L1200). I made a [fork with fixes](https://github.com/libyal/libewf/compare/main...taco-paco:libewf:main?diff=split) if there're no objections/issues I can open upstream pr.

**Comment by taco-paco** [comment]
If call `libewf_internal_handle_open_file_io_pool` results with error then variable `result` [will be set](https://github.com/libyal/libewf/blob/fc1ed7b7bd83a6a65dcc3bf38d7f696735734d7a/libewf/libewf_handle.c#L1172) to smth other then 1. Then [inside if](https://github.com/libyal/libewf/blob/fc1ed7b7bd83a6a65dcc3bf38d7f696735734d7a/libewf/libewf_handle.c#L1192) we set it to `-1` but unlike in other cases we don't exit function. So when we reach call to [libcthreads_read_write_lock_release_for_write](https://github.com/libyal/libewf/blob/fc1ed7b7bd83a6a65dcc3bf38d7f696735734d7a/libewf/libewf_handle.c#L1200) which executes with success it will set `result` to valid value 1. As result we will exit function successfully with `internal_handle->file_io_pool` uninitialized which I think is incorrect behaviout

**Comment by joachimmetz** [comment]
Ah if that is the issue you're pointing out, that's a matter of not setting result by libcthreads_read_write_lock_release_for_write. I'll make the necessary changes.

**Comment by joachimmetz** [comment]
@taco-paco thx for flagging, changes in https://github.com/libyal/libewf/commit/3ba79a6b83b8e5c8b2a928a204cf8baa71d369d8
