### ISSUE TITLE
Current status of the libewf library?

### ISSUE THREAD

**Issue by anaumchev** [libyal/libewf#173]
Hello!
Could you please kindly let me know the current status of the libewf library development?
Thanks!

**Comment by joachimmetz** [comment]
It's in the README: https://github.com/libyal/libewf#readme. Or do you have any specific questions?

**Comment by anaumchev** [comment]
> It's in the README: https://github.com/libyal/libewf#readme. Or do you have any specific questions?

The specific question is: is the project still alive? I am asking because the last commit was back in August, the commit did not pass automated checks, and no follow-up action was taken.

**Comment by joachimmetz** [comment]
1. what do you main with alive? being worked on? being maintained? if you read the README you would have seen this is experimental, WIP, development 
2. I don't understand your logic what does a failing CI test have to do with if a project is still being worked on or not?

what is the reason for asking? are you planning to help out?

**Comment by anaumchev** [comment]
> 1. what do you main with alive? being worked on? being maintained? if you read the README you would have seen this is experimental, WIP, development
> 2. I don't understand your logic what does a failing CI test have to do with if a project is still being worked on or not?
> 
> what is the reason for asking? are you planning to help out?

I was thinking of adding a dependency on libewf in my software.
Thanks, you gave all the information I need.

**Comment by joachimmetz** [comment]
> I was thinking of adding a dependency on libewf in my software.

Without more specific details what this software does and for what purpose. I cannot help you. Last commit and CI test status seem like a very weak software selection process to me.
