### ISSUE TITLE
pyewf_test_handle.py is missing in source package

### ISSUE THREAD

**Issue by vwegert** [libyal/libewf#174]
Similar to [this](https://github.com/libyal/libfwnt/issues/12) and [this](https://github.com/libyal/libwrc/issues/1) issue: The file `tests/pyewf_test_handle.py` is present in the main Git repository, but missing in the released source packages. This causes the test to fail when run with `make check`. Manually adding the file from the master repository fixes the issue locally.

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libewf/commit/097a70997be07460f9ac1b1c732d9a53c773646c
