### ISSUE TITLE
How do I read files from an e01 or ex01 segment file set in C#?

### ISSUE THREAD

**Issue by Ladwaldez** [libyal/libewf#175]
I want to export the names of the files in the content of the .e01 and .ex01 (encase) files and the file I want. I want to export the names of the files in the contents of e01 and .ex01 (encase) files and the file I want. Can you suggest a sample code block that I can use for this process, thanks in advance.

**Comment by joachimmetz** [comment]
> I want to export the names of the files in the content of the .e01 and .ex01 (encase) files and the file I want.

EWF files are a container format, there is typically a storage media (disk) image in there. libewf will only expose the data in an E01 or Ex01 as the raw storage media data.

**Comment by Ladwaldez** [comment]
can you help me how to do it

**Comment by joachimmetz** [comment]
> can you help me how to do it

You don't seem to understand the problem domain. What you want requires a lot of additional other code. Get a better understanding of that problem domain first then come back with more concrete questions.

**Comment by joachimmetz** [comment]
Closing out of scope of this project
