### ISSUE TITLE
configure with zlib fails

### ISSUE THREAD

**Issue by CanuteTheGreat** [libyal/libewf#177]
Hello!

When running './configure --with-zlib' the script fails:
<snipped>
checking whether to use search for zlib in includedir and libdir or in the specified DIR, or no if not to use zlib... (cached) yes
configure: error: in `/home/canutethegreat/Downloads/libewf/libewf-20201230':
configure: error: no such directory: yes
See `config.log' for more details

Previous versions compiled fine with zlib so I am not sure if that is expected nor not.

**Comment by joachimmetz** [comment]
Can you attach config.log ?

**Comment by joachimmetz** [comment]
Never mind you're holding it wrong per `configure --help` this is how to use the `--with-zlib` option

```
  --with-zlib[=DIR]       search for zlib in includedir and libdir or in the
                          specified DIR, or no if not to use zlib
                          [default=auto-detect]
```

**Comment by CanuteTheGreat** [comment]
Ah, RTFM indeed. --with-zlib=auto-detect does in fact work.
