### ISSUE TITLE
Cannot install most recent release on linux

### ISSUE THREAD

**Issue by Rafiot** [libyal/libewf#182]
Installing the release from yesterday (20230212) doesn't work on linux, and I think (?) it is because there are no appropriate wheel packages, and the the source is also missing on PyPi: https://pypi.org/project/libewf-python/#files

**Comment by joachimmetz** [comment]
@Rafiot this is the experimental version, https://github.com/libyal/libewf/releases/tag/20230212 says clearly `Pre-release of version 20230212, for testing purposes` this is not a release for end users.

**Comment by Rafiot** [comment]
Noted, it's not flagged as such on PyPI, sorry for the bother.

**Comment by joachimmetz** [comment]
PyPI has no such notion/functionality unfortunately
