### ISSUE TITLE
Wiki improvement ideas

### ISSUE THREAD

**Issue by Entwicklungsleiter** [libyal/libewf#183]
Moin!

For wiki description how to build libewf from source I have some ideas (after succeeding build deb packages myself):

In area "Using Debian package tools (DEB)" please add some small infos to commandline example:

make && make dist-gzip # to build the tar ball
mv libewf-<version>.tar.gz ../libewf-<version>.orig.tar.gz # move tarball above where dpkg-buildpackage will search for it
cp -rf dpkg debian
dpkg-buildpackage -rfakeroot -b # add parameter -b to make process successful

**Comment by joachimmetz** [comment]
Thx for the suggestions but the wiki is not intended as a complete guide to "Using Debian package tools (DEB)" 

Also if you read https://github.com/libyal/libewf/wiki/Building#read-first it is recommended to use a source distribution package, not build one yourself.
