### ISSUE TITLE
git clone and cd libewf

### ISSUE THREAD

**Issue by zdavatz** [libyal/libewf#184]
1. this works: git clone https://github.com/libyal/libewf.git
2. this works: cd libewf/
3. this does not work: ./synclibs.sh
4. this does not work: ./autogen.sh
5. ![latest-screenshot](https://user-images.githubusercontent.com/4953/225562798-4e57fbc2-c043-4cb2-a5ec-7b231337d208.png)

**Comment by joachimmetz** [comment]
@zdavatz if you're not a developer this method of building the source is not for you. The scripts work fine, since they are run as part of the CI tests. Use the source distribution package as recommended on https://github.com/libyal/libewf/wiki/Building#read-first instead

**Comment by zdavatz** [comment]
this worked now: ./synclibs.sh

but it seems that my Orcale Linux has an old version of gettext:
```
autoreconf: autopoint failed with exit status: 1
[opc@free libewf]$ sudo yum install gettext
Failed to set locale, defaulting to C.UTF-8
Letzte Prüfung auf abgelaufene Metadaten: vor 3:59:18 am Thu Mar 16 04:53:15 2023.
Das Paket gettext-0.19.8.1-17.el8.x86_64 ist bereits installiert.
Abhängigkeiten sind aufgelöst.
Nichts zu tun.
Fertig.
```

**Comment by joachimmetz** [comment]
Stick with the source distribution package. If you're not directly developing libewf there is no reason to use `git clone`

**Comment by zdavatz** [comment]
In my view using git clone should be the easiest way to build any project including yours. It is how I build the Linux kernel. Why are you recommending not to use the libewf package via `yum install`? What is wrong with that?

**Comment by joachimmetz** [comment]
> Why are you recommending not to use the libewf package via yum install? 

you don't seem to understand the ecosystem, I have no control over what get's distributed via "yum", this also is distro dependent.

**Comment by joachimmetz** [comment]
> In my view using git clone should be the easiest way to build any project including yours.

This project assumes that you have a fair bit of understanding of how to build from source to do so.
