### ISSUE TITLE
unable to build with mingw

### ISSUE THREAD

**Issue by lld1995** [libyal/libewf#190]
mingw32-make[1]: Entering directory 'D:/opensource/libewf/libclocale'
C:/msys64/usr/bin/sh.exe ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../common  -DLOCALEDIR=\"/ucrt
64/share/locale\" -I../include -I../common -I../libcerror  -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DFUSE_USE_VERS
ION=26 -D_FILE_OFFSET_BITS=64  -g -O2 -Wall -MT libclocale_codepage.lo -MD -MP -MF .deps/libclocale_codepage.Tpo -c -o
libclocale_codepage.lo libclocale_codepage.c
Xlibclocale_codepage.Tpo -c -o libclocale_codepage.lo libclocale_codepage.lo
libtool: warning: libobj name 'libclocale_codepage.Tpo -c -o libclocale_codepage.lo libclocale_codepage.lo' may not con
tain shell special characters.
rm: unknown option -- c
Try 'rm --help' for more information.
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common "-DLOCALEDIR=\\/ucrt64/share/locale\" -I../include -I../common -
I../libcerror -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64 -g -O2 -Wall -M
T libclocale_codepage.lo -MD -MP -MF .deps/libclocale_codepage.Tpo -c -o libclocale_codepage.lo libclocale_codepage.c"
 -DDLL_EXPORT -DPIC -o .libs/libclocale_codepage.Tpo -c -o libclocale_codepage.lo libclocale_codepage.o
gcc.exe: warning: libclocale_codepage.o: linker input file unused because linking not done
gcc.exe: error: libclocale_codepage.o: linker input file not found: No such file or directory
mingw32-make[1]: *** [Makefile:755: libclocale_codepage.lo] Error 1
mingw32-make[1]: Leaving directory 'D:/opensource/libewf/libclocale'
mingw32-make: *** [Makefile:875: all-recursive] Error 1

version : MinGW-W64-builds-5.0.0

**Comment by joachimmetz** [comment]
mingw CI tests are working fine https://ci.appveyor.com/project/libyal/libewf, so this looks like an issue in your build environment

```
libtool: warning: libobj name 'libclocale_codepage.Tpo -c -o libclocale_codepage.lo libclocale_codepage.lo' may not con
tain shell special characters.
rm: unknown option -- c
Try 'rm --help' for more information.
```

**Comment by lld1995** [comment]
i use vs instead
