### ISSUE TITLE
How do I upgrade autotools?

### ISSUE THREAD

**Issue by ishitar2021** [libyal/libewf#194]
i used "How to build from source: https://github.com/libyal/libewf/wiki/Building" link to build my source code of libewf.
i have done the following things 
`git clone https://github.com/libyal/libewf.git
cd libewf/
./synclibs.sh
./autogen.sh`
and in last `./autogen.sh` when run first it showed some libraries are missing . so i installed that all like getext and autoconf. but autoconf i had 2.64 version and manually i installed the 2.71 version. but in libewf folder its taken the older version as i run the command i saw error like this

    `root@pooja-hcl-desktop:/home/pooja/Documents/libewf# ./autogen.sh
    configure.ac:1: error: Autoconf version 2.71 or higher is required
    configure.ac:1: the top level
    autom4te: /usr/bin/m4 failed with exit status: 63
    aclocal: error: echo failed with exit status: 63
    autoreconf: aclocal failed with exit status: 63`

then i googled it and found to change the path  to be added to that file autogen.sh script:

`AUTOCONF=/path/to/downloaded/autoconf-2.71 ./autogen.sh`
then the error occurred as 
`root@pooja-hcl-desktop:/home/pooja/Documents/libewf# ./autogen.sh`
`./autogen.sh`:` 43: ./autogen.sh: Cannot fork`
    `Can't fork, trying again in 5 seconds at /usr/share/autoconf/Autom4te/General.pm line 307.
    Can't fork, trying again in 5 seconds at /usr/share/autoconf/Autom4te/General.pm line 307.
    Can't fork, trying again in 5 seconds at /usr/share/autoconf/Autom4te/General.pm line 307.
    Can't fork, trying again in 5 seconds at /usr/share/autoconf/Autom4te/General.pm line 307.
    Can't fork, trying again in 5 seconds at /usr/share/autoconf/Autom4te/General.pm line 307.
    Can't fork, trying again in 5 seconds at /usr/share/autoconf/Autom4te/General.pm line 307.`
and continuing like this. 

What should i do to rectify this

Need to build libewf fully

**Comment by joachimmetz** [comment]
You'll need to update your version of autotools. Why don't you use a source distribution package, what you are trying to do is only intended for people familiar with autotools that develop libewf.

**Comment by ishitar2021** [comment]
> You'll need to update your version of autotools. Why don't you use a source distribution package, what you are trying to do is only intended for people familiar with autotools that develop libewf.

i have installed all the packages through synaptic package manager. so as iam using ubuntu 18.04 version 
my package version is autotools-dev 2018224.1 .
and my autoconf version was 2.64 in synaptic. so i manually installed the higher version 2.71 but it didnt work for me.

**Comment by joachimmetz** [comment]
> and my autoconf version was 2.64 in synaptic. so i manually installed the higher version 2.71 but it didnt work for me.

that's an issue on your configuration, the scripts and autotools are working fine in the CI tests. Closing this issue given it is not a libewf issue.
