### ISSUE TITLE
Where are E01 files stored?

### ISSUE THREAD

**Issue by zsymdsy** [libyal/libewf#195]
I used the libewf library to generate two files in a multi-threaded environment, one is E:\Test3. E01, and the other is G:\Test4. E01.
After generating them, I found that both files exist in the E:\ directory, but there are no files in the G:\ directory.

**Comment by joachimmetz** [comment]
@zsymdsy can you be more specific about the actual test configuration and commands you ran?

**Comment by zsymdsy** [comment]
> @zsymdsy can you be more specific about the actual test configuration and commands you ran?

**Comment by zsymdsy** [comment]
> @zsymdsy can you be more specific about the actual test configuration and commands you ran?
1. Use multiple threads to generate multiple E01 files.
2. Set the path of each E01 file to be saved **in the root path of different partitions**. Each partition has enough free space.
Other than that, there is nothing else to configure.

**Comment by joachimmetz** [comment]
```
Use multiple threads to generate multiple E01 files.
Set the path of each E01 file to be saved in the root path of different partitions. Each partition has enough free space.
Other than that, there is nothing else to configure.
```

Not sure what you mean with this the ewfaquire will only create 1 E01 file per storage media image

@zsymdsy if you don't provide me representative examples I cannot help you.

**Comment by joachimmetz** [comment]
Without the actual code and/or necessary context on how you are using the library, I am not able to help you. Are you using the same handle ?

**Comment by joachimmetz** [comment]
I'll close this issue unless you are able provide me the necessary details, I don't have time for these back and forths.

**Comment by zsymdsy** [comment]
`	if( ( path_type != LIBCPATH_TYPE_DEVICE )
	 && ( path_type != LIBCPATH_TYPE_EXTENDED_LENGTH )
	 && ( path_type != LIBCPATH_TYPE_EXTENDED_LENGTH_UNC )
	 && ( path_type != LIBCPATH_TYPE_UNC ) )
	{
		if( libcpath_path_get_current_working_directory_by_volume_wide(
		     volume_name,
		     volume_name_length,
		     &current_directory,
		     &current_directory_size,
		     error ) != 1 )
		{
			libcerror_error_set(
			 error,
			 LIBCERROR_ERROR_DOMAIN_RUNTIME,
			 LIBCERROR_RUNTIME_ERROR_GET_FAILED,
			 "%s: unable to retrieve current working directory by volume.",
			 function );

			goto on_error;
		}
		/* Determine the volume name using the current working directory if necessary
		 */
		if( libcpath_path_get_volume_name_wide(
		     current_directory,
		     current_directory_size - 1,
		     &volume_name,
		     &volume_name_length,
		     &current_directory_name_index,
		     error ) != 1 )
		{
			libcerror_error_set(
			 error,
			 LIBCERROR_ERROR_DOMAIN_RUNTIME,
			 LIBCERROR_RUNTIME_ERROR_GET_FAILED,
			 "%s: unable to determine volume name from current working directory.",
			 function );

			goto on_error;
		}
	}`

I found the problem.
The above code will cause problems in a multi-threaded environment.
Because each thread is using SetCurrentDirectory and GetCurrentDirectory, this will conflict.

**Comment by joachimmetz** [comment]
Unable to action this due to reporter unable to describe necessary context.

Per [README ](https://github.com/libyal/libewf/blob/main/README) Work in progress "Multi-threading support" and "experimental". Closing issue.
