### ISSUE TITLE
Possible mistake && instead of || ?

### ISSUE THREAD

**Issue by LTRData** [libyal/libewf#196]
Possible mistake && instead of || ? Or am I missing something else here maybe?

https://github.com/libyal/libewf/blob/9035e3824fc2e7963bfac959d595f5e904d0bc50/libewf/libewf_handle.c#L10380C3-L10380C3

**Comment by joachimmetz** [comment]
Thanks for flagging, changes in https://github.com/libyal/libewf/commit/b989a33f9e6c798ac26f6440aea03727d8c50fb8
