### ISSUE TITLE
LIBEWF_FORMAT_FTK and LIBEWF_FORMAT_LVF deprecated. What should use?

### ISSUE THREAD

**Issue by D3vil0p3r** [libyal/libewf#197]
I'm compiling an old tool called [guymager](https://sourceforge.net/projects/guymager/files/guymager/LatestSource/) that seems to use `LIBEWF_FORMAT_FTK`. Indeed, when I compile it, I get the error:
```sh
config.cpp:297:30: error: 'LIBEWF_FORMAT_FTK' was not declared in this scope; did you mean 'LIBEWF_FORMAT_EWF'?
  297 |       {  "FTK"     ,         LIBEWF_FORMAT_FTK    },
      |                              ^~~~~~~~~~~~~~~~~
      |                              LIBEWF_FORMAT_EWF
make: *** [Makefile:992: config.o] Error 1
```
I guess that the latest versions of libewf removed it. What should be the replacement of it? `LIBEWF_FORMAT_EWF` or `LIBEWF_FORMAT_FTK_IMAGER`? Or another one?

I have the same issue for `LIBEWF_FORMAT_LVF`. Should I use `LIBEWF_FORMAT_LOGICAL_ENCASE5`?

**Comment by joachimmetz** [comment]
First of all this is the experimental version of libewf and not recommended for production purposes, use https://github.com/libyal/libewf-legacy/tree/main instead.

LIBEWF_FORMAT_LVF and LIBEWF_FORMAT_FTK have been on the deprecation list for a while
https://github.com/libyal/libewf-legacy/blob/main/include/libewf/definitions.h.in#L94
