### ISSUE TITLE
Time estimate appears to use integer GB to calculate estimate

### ISSUE THREAD

**Issue by gregfreemyer** [libyal/libewf#21]
Using ewfacquire 20140608 (not the newer experimental release).

I happen to notice the initial time estimate can be way off, but then it jumps drastically on the 1GB updates.

It's like the code does something like:

time_remaining = total_GB * (time_in_progress / int(GB_done))

Thus in the first few GB the error is pretty drastic.  In particular, my 2 1/2 hour image was estimating 5 hours at the 1.9 GB process stage, but then corrected to 2 1/2 hours on the next update.

**Comment by gregfreemyer** [comment]
I just watched another image more closely.  The miss calculation seems to be more like every 5 billion bytes.  That is I watched and at 5GB, 20GB and 25GB the time estimate made a significant jump.

Note those are power of 10 GB, not GiB.

**Comment by joachimmetz** [comment]
It's an estimate, what do you expect? Also is this with or without empty block compression?

**Comment by gregfreemyer** [comment]
By chance I saw the issue with fast / empty block compression and with no compression at all.

And it is clearly not a big deal, but it also looks trivial to fix.  If you don't know off hand where the fix is maybe I'll take a look at the code and try to put together a patch.

**Comment by joachimmetz** [comment]
There is nothing to fix, this is working as intended. You cannot stop the estimate from jumping, since the situation changes continuous.

**Comment by gregfreemyer** [comment]
I'll see if I can "improve" the estimate and then send you a patch.

**Comment by gregfreemyer** [comment]
Okay.  Looking at the code the issue is the "new_percentage" is only tracked as an integer and there is a big difference between being 1.0% complete and being 1.9% complete.

Below is my patch which definitely fixes the time estimate and from what I see it also improves the throughput number, but I don't know the coding style so it is probably easier for you to rewrite it instead of just applying it.

Index: libewf-20150126/ewftools/process_status.c
===================================================================
--- libewf-20150126.orig/ewftools/process_status.c
+++ libewf-20150126/ewftools/process_status.c
@@ -347,6 +347,7 @@ int process_status_update(
        int64_t remaining_number_of_seconds = 0;
        int64_t total_number_of_seconds     = 0;
        int8_t new_percentage               = 0;
+       float new_percentage_float          = 0.0;
 
        if( process_status == NULL )
        {
@@ -366,7 +367,8 @@ int process_status_update(
                if( ( bytes_total > 0 )
                 && ( bytes_read > 0 ) )
                {
-                       new_percentage = (int8_t) ( ( bytes_read * 100 ) / bytes_total );
+                       new_percentage_float = ((float) ( bytes_read * 100 )) / bytes_total ;
+                       new_percentage = (int8_t) ( new_percentage_float );
                }
                if( libcdatetime_elements_set_current_time_localtime(
                     process_status->current_time_elements,
@@ -459,7 +461,7 @@ int process_status_update(
 
                        if( new_percentage > 0 )
                        {
-                               total_number_of_seconds     = ( ( number_of_seconds * 100 ) / new_percentage );
+                               total_number_of_seconds     = ( ( number_of_seconds * 100 ) / new_percentage_float );
                                remaining_number_of_seconds = total_number_of_seconds - number_of_seconds;
 
                                /* Negative time means nearly finished

**Comment by joachimmetz** [comment]
Floating point calculations are more expensive. As said before this is not an issue.

**Comment by gregfreemyer** [comment]
The same patch using ints is below.  Pick it up or not.  I find it a useful improvement.  For now I will carry it in my openSUSE package.

<pre><code>
Index: libewf-20150126/ewftools/process_status.c
===================================================================
--- libewf-20150126.orig/ewftools/process_status.c
+++ libewf-20150126/ewftools/process_status.c
@@ -347,6 +347,7 @@ int process_status_update(
        int64_t remaining_number_of_seconds = 0;
        int64_t total_number_of_seconds     = 0;
        int8_t new_percentage               = 0;
+       int16_t new_percentage_x_100        = 0;
 
        if( process_status == NULL )
        {
@@ -366,7 +367,9 @@ int process_status_update(
                if( ( bytes_total > 0 )
                 && ( bytes_read > 0 ) )
                {
-                       new_percentage = (int8_t) ( ( bytes_read * 100 ) / bytes_total );
+                       /* assumes bytes_read is <= 922 TB or 64-bit int will overflow */
+                       new_percentage_x_100 = (int16_t) (( bytes_read * 100 * 100 ) / bytes_total) ;
+                       new_percentage = (int8_t) ( new_percentage_x_100 / 100 );
                }
                if( libcdatetime_elements_set_current_time_localtime(
                     process_status->current_time_elements,
@@ -459,7 +462,8 @@ int process_status_update(
 
                        if( new_percentage > 0 )
                        {
-                               total_number_of_seconds     = ( ( number_of_seconds * 100 ) / new_percentage );
+                               total_number_of_seconds     = ( ( number_of_seconds * 100 * 100 ) / new_percentage_x_100 );
                                remaining_number_of_seconds = total_number_of_seconds - number_of_seconds;
 
                                /* Negative time means nearly finished

</code></pre>

**Comment by joachimmetz** [comment]
Why not 1000 instead of 100? I shall consider your changes as a low prio addition to the experimental release when I have time. However it will only provide slight less flux in the small numbers. The behaviour the estimate dropping significantly half way the disk will typically still happen.

**Comment by gregfreemyer** [comment]
Can't say I thought about 100 vs 1000.

I can say the current code at 1.9999% complete over estimates the time remaining by 99.99% thus 3 hours remaining based on float math becomes 6 hours remaining with the current int math.

With the x_100 patch it would still be 0.99% of an over estimate, thus 3 hours become 3 hours 1.8 minutes.  As you note that 0.99% over estimate is below the noise level.

**Comment by joachimmetz** [comment]
At ~2% progress the reliability of saying anything about the reliability or noise level is like looking into a crystal ball.

**Comment by gregfreemyer** [comment]
For some reason I don't understand the x_100 patch breaks ewfverify status reporting.  The percentage is stuck at 0% even as far in as 5%.  (I killed it then and tested with the unpatched version to confirm the patch was causing the problem.)

I would like to understand what is going on so I will do more troubleshooting later and submit a different patch.

**Comment by joachimmetz** [comment]
When I have time to work on this. I'll revisit the underlying idea for the experimental version. As already indicated multiple times, this currently is a low priority on my large to do list.
