### ISSUE TITLE
libewf 20150126 problems handling E01 images with > 64 file segments

### ISSUE THREAD

**Issue by jbolas** [libyal/libewf#22]
I have multiple examples of E01 images, created using FTK Imager, with more than 64 file segments. The current version of ewfverify fails on these images. However, ewfverify 20140608 works correctly when opening and verifying the images. 

Steps to reproduce: 

1. create two E01 images of the same physical drive, such that the first image has 64 segments or less (i.e., the last segment having an extension of .E64 or lower) and the second image has 65 segments or more (ending with .E65 or higher).
2. Use a separate tool to verify the hash values of the data in each image.
3. Use ewfverify 20140608 to verify each image. Both should be successful.
4. Use ewfverify 20150126 to verify each image. The first should succeed and the second should fail.

I note that, in December 2014, the constant LIBEWF_MAXIMUM_CACHE_ENTRIES_SEGMENT_FILES was changed to 64.
https://github.com/libyal/libewf/blame/master/libewf/libewf_definitions.h.in#L440
Is it possible that this change to the size of the segment_files_cache in a segment_table could be related?

**Comment by jonstewart** [comment]
git bisect confirms [66ede5c8e5dc6e528180bb881d66a8b81968ce40](https://github.com/libyal/libewf/commit/66ede5c8e5dc6e528180bb881d66a8b81968ce40) as the bad commit.

**Comment by joachimmetz** [comment]
Yes this could be related the current git checked-in version is still experimental as indicated. I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
Added test: https://github.com/libyal/libewf/commit/9f2f808bf9862752aa83f84a07ff54b252968560

Able to reproduce the issue:
```
Unable to verify input.
libewf_chunk_data_initialize_clear_data: unable to create data.
libewf_chunk_table_get_chunk_data_by_offset: unable to create chunk: 32082 data.
libewf_handle_read_buffer: unable to read chunk: 32082 data.
verification_handle_read_buffer: unable to read storage media buffer.
verification_handle_verify_input: unable to read data.
ewfverify: FAILURE
```

**Comment by joachimmetz** [comment]
https://github.com/libyal/libewf/commit/743a2bdd93d73da940b56526a40fcc576ca89f3b should address the issue.
