### ISSUE TITLE
Exporting an image to stdout with ewfexport appends exit status to image body 

### ISSUE THREAD

**Issue by badmd5** [libyal/libewf#23]
When using ewfexport to send an image to stdout, it will append the string "ewfexport: SUCCESS" to end of the image on completion. Receiving programs will interpret this string as part of the image body. For example, here someprogram will not be working with an exact copy of a raw image, but has 19 additional bytes at the end...

ewfexport -u -f raw -t - image.E01 | someprogram

Maybe that exit message should go to stderr instead, when stdout is used for the image?

**Comment by joachimmetz** [comment]
This sounds like a bug. I'll have a look when time permits.

**Comment by joachimmetz** [comment]
Reproduced and fixed.
