### ISSUE TITLE
Fails to build with recent libcstring

### ISSUE THREAD

**Issue by xambroz** [libyal/libewf#26]
Build on Fedora linux fails with the undefined reference to the libcstring_narrow_string_length and libcstring_narrow_string_copy. It seems that such function is no longer in libcstring.

I have tried with both release 20150126 (5e47a75e30a4dd3068f8210f0a62c37b58329d7f) and current head commit (54b0eada69defd015c49e4e1e1e4e26a27409ba3)

This is the error message I get during build.
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wall  -Wl,-z,relro  -o ewfacquirestream byte_size_string.o digest_hash.o ewfacquirestream.o ewfinput.o ewfoutput.o guid.o imaging_handle.o log_handle.o platform.o process_status.o storage_media_buffer.o -luuid -lhmac -lcsystem -lcsplit -lcdatetime ../libewf/libewf.la -lcnotify -lclocale -lcerror -lcstring  -lbz2 
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wall  -Wl,-z,relro  -o ewfdebug byte_size_string.o ewfdebug.o ewfinput.o ewfoutput.o -lcsystem ../libewf/libewf.la -lcnotify -lclocale -lcerror -lcstring  -lbz2 
libtool: link: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wall -Wl,-z -Wl,relro -o .libs/ewfacquire byte_size_string.o digest_hash.o device_handle.o ewfacquire.o ewfinput.o ewfoutput.o guid.o imaging_handle.o log_handle.o platform.o process_status.o storage_media_buffer.o  -lodraw -lsmdev -lsmraw -luuid -lcsystem -lcdatetime ../libewf/.libs/libewf.so -L/usr/lib64 -lcdata -lcsplit -luna -lcfile -lcpath -lbfio -lfcache -lfdata -lfvalue -lz -lhmac -lcaes -lcnotify -lclocale -lcthreads -lcerror -lcstring -lbz2
libtool: link: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wall -Wl,-z -Wl,relro -o .libs/ewfacquirestream byte_size_string.o digest_hash.o ewfacquirestream.o ewfinput.o ewfoutput.o guid.o imaging_handle.o log_handle.o platform.o process_status.o storage_media_buffer.o  -luuid -lcsystem -lcdatetime ../libewf/.libs/libewf.so -L/usr/lib64 -lcthreads -lcdata -lcsplit -luna -lcfile -lcpath -lbfio -lfcache -lfdata -lfvalue -lz -lhmac -lcaes -lcnotify -lclocale -lcerror -lcstring -lbz2
libtool: link: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wall -Wl,-z -Wl,relro -o .libs/ewfdebug byte_size_string.o ewfdebug.o ewfinput.o ewfoutput.o  -lcsystem ../libewf/.libs/libewf.so -L/usr/lib64 -lcthreads -lcdata -lcsplit -luna -lcfile -lcpath -lbfio -lfcache -lfdata -lfvalue -lz -lhmac -lcaes -lcnotify -lclocale -lcerror -lcstring -lbz2
../libewf/.libs/libewf.so: undefined reference to `libcstring_narrow_string_length'
../libewf/.libs/libewf.so: undefined reference to `libcstring_narrow_string_copy'
collect2: error: ld returned 1 exit status
Makefile:1091: recipe for target 'ewfacquire' failed
make[1]: *** [ewfacquire] Error 1
make[1]: *** Waiting for unfinished jobs....
ewfacquirestream.o: In function `ewfacquirestream_read_chunk':
/home/mambroz/rpmbuild/BUILD/libewf-54b0eada69defd015c49e4e1e1e4e26a27409ba3/ewftools/ewfacquirestream.c:326: undefined reference to `libcsystem_file_io_read'
../libewf/.libs/libewf.so: undefined reference to `libcstring_narrow_string_length'
../libewf/.libs/libewf.so: undefined reference to `libcstring_narrow_string_copy'
collect2: error: ld returned 1 exit status
Makefile:1095: recipe for target 'ewfacquirestream' failed
make[1]: *** [ewfacquirestream] Error 1
../libewf/.libs/libewf.so: undefined reference to `libcstring_narrow_string_length'
../libewf/.libs/libewf.so: undefined reference to `libcstring_narrow_string_copy'
collect2: error: ld returned 1 exit status
Makefile:1099: recipe for target 'ewfdebug' failed
make[1]: *** [ewfdebug] Error 1
make[1]: Leaving directory '/home/mambroz/rpmbuild/BUILD/libewf-54b0eada69defd015c49e4e1e1e4e26a27409ba3/ewftools'
Makefile:804: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.nGlIJ0 (%build)

```

**Comment by xambroz** [comment]
Here is paste from the whole build:
http://ur1.ca/myupt

BTW there are some warnings about implicid declarations as well - possibly some includes missing.
Best regards
Michal Ambroz

**Comment by joachimmetz** [comment]
This is the experimental version of libewf, I recommend sticking with the stable version for now: https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/

**Comment by xambroz** [comment]
Hi Joachim,
I understand it is experimental, but to get all the dependencies to Fedora (21 libraries) will take at least year with all the formal processes there :). Until then I guess it will be rock stable.

Anyway ... there is probably no reason even for the experimental branch to fail to build, is it ;) ?
I will try to patch.

**Comment by gregfreemyer** [comment]
On Tue, Jun 30, 2015 at 3:29 PM, xambroz <notifications@github.com> wrote:

> Hi Joachim,
> I understand it is experimental, but to get all the dependencies to Fedora
> (21 libraries) will take at least year with all the formal processes there
> :). Until then I guess it will be rock stable.
>

Unfortunately the stable version has a memory exhaustion bug in ewfverify,
so it can run out of RAM before verifying a large image.

https://github.com/libyal/libewf/issues/2

I tend to see it with 1 TB and larger images, but it varies based on how
much RAM you have.

I typically run without swap, so I can't say anything about if having swap
works around the problem or not.

I make all my images with libewf stable.  If verify fails with an out of
RAM issue I move it to a system with libewf experimental on it and re-do
the verify.

So far, that combination is working for me.

Greg

**Comment by xambroz** [comment]
Thanks Greg for sharing the usecase hint.

**Comment by joachimmetz** [comment]
> Anyway ... there is probably no reason even for the experimental branch to fail to build, is it ;) ?

experimental is explained here: https://github.com/libyal/libyal/wiki

**Comment by uckelman** [comment]
I believe what's missing in this case is an `#include "libewf_libcstring.h"` near the top of libewf_case_data.c.

**Comment by joachimmetz** [comment]
Could very well be, I just need time to get back to working on the experimental version. As indicated I opt to stick with the stable version, largely since this is not the only issue that needs to be addressed.

**Comment by joachimmetz** [comment]
Added missing include (pending commit).
