### ISSUE TITLE
incomplete format list in ewfacquire and ewfexport man pages

### ISSUE THREAD

**Issue by uckelman** [libyal/libewf#27]
`ewfacquire -h` and `ewfexport -h` list `encase7-v2` among the possible arguments for the `-f` flag. The man pages for `ewfacquire` and `ewfexport` do not list `encase7-v2` as one of the arguments for the `-f` flag. The man page should be updated to reflect what's supported.

**Comment by joachimmetz** [comment]
As indicated here: https://github.com/libyal/libewf/issues/4 this is still work in progress

**Comment by uckelman** [comment]
I know---I thought it would be good to mention it so that it isn't missed.
