### ISSUE TITLE
TP_POOL support not implemented yet on Visual Studio 2013

### ISSUE THREAD

**Issue by gbstack** [libyal/libewf#28]
When I try to build libewf_dll project, I got following error from Visual Studio
**TP_POOL support not implemented yet on Visual Studio 2013**

The error is caused by following line from libcthreads_thread_pool.c file
> #if defined( WINAPI ) && ( WINVER >= 0x0602 )
> /* TODO */
> #error TP_POOL support not implemented yet

**Comment by joachimmetz** [comment]
Ypu'll need to set WINVER to the version of WINAPI < 0x0602. Also see:
https://github.com/libyal/libewf/wiki/Building#building

Or feel free to add TP_POOL support to libcthreads.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libcthreads/issues/3
