### ISSUE TITLE
Feature request: Progress display to only update at percentage points.

### ISSUE THREAD

**Issue by hydrocloricacid** [libyal/libewf#30]
Would like to have a way to disable the constant progress display entries so that the only progress display entries are for each percentage points. (e.g. for 1% 2% ... etc)

It is really just asking to for a method to get the behaviour of libewf_20100226 or similar as seen in the ewf-tools package in debian squeeze.
( https://packages.debian.org/squeeze/ewf-tools )

This will help me to work around issue 16 where there is an problem with progress updates under windows.
ref:  https://github.com/libyal/libewf/issues/16

**Comment by joachimmetz** [comment]
My time is very limited at the moment to work on this, but I'll have a look as soon time permits

**Comment by hydrocloricacid** [comment]
understand.

I'll look into this myself also.

**Comment by joachimmetz** [comment]
> Would like to have a way to disable the constant progress display entries so that the only progress display entries are for each percentage points. (e.g. for 1% 2% ... etc)

The reason why this approach was dropped:
* the status update take a long time without any status updates e.g. 1% of 2TiB is 20GiB
* the acquisition speed will affect the status update and typically you want to know the acquisition speed relatively fast to correct potential issues (e.g. wrong USB port) early

**Comment by joachimmetz** [comment]
The process update issue in Windows was addressed, closing this issue.
