### ISSUE TITLE
Unable to get pyewf, pyqcow, pyvmdk working in plaso

### ISSUE THREAD

**Issue by dfirence** [libyal/libewf#31]
I am running an Arch  64 build: 
```
Linux ARCHIR 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

[ Problem ]:
No matter what I do, following your instructions on building from source does not allow me to 'apparently' install the libraries correctly.  I say apparently because the PLASO RUNTESTS.PY script reports these libraries as missing.  

What should I do?

See below.
```
$ python2 ./run_tests.py
Checking availability and versions of plaso dependencies.
[OK]            artifacts version: 20150409
[OK]            bencode
[OK]            binplist version: 0.1.4
[OK]            construct version: 2.5.2
[OK]            dateutil version: 2.4.2
[OK]            dfvfs version: 20151231
[OK]            dpkt version: 1.8
[OK]            google.protobuf
[OK]            hachoir_core version: 1.3.3
[OK]            hachoir_parser version: 1.3.4
[OK]            hachoir_metadata version: 1.3.3
[OK]            IPython version: 4.0.0
[OK]            pefile version: 1.2.10-139
[OK]            psutil version: 3.3.0
[OK]            pyparsing version: 2.0.7
[OK]            pytz
[OK]            requests version: 2.9.1
[OK]            six version: 1.10.0
[OK]            sqlite3 version: 3.9.2
[OK]            yaml version: 3.11
[OK]            SleuthKit version: 4.2.0
[OK]            pytsk3 version: 20150406
[OK]            libbde (pybde) version: 20160108
[OK]            libesedb (pyesedb) version: 20160107
[OK]            libevt (pyevt) version: 20160107
[OK]            libevtx (pyevtx) version: 20160107
[FAILURE]       missing: pyewf.
[OK]            libfwsi (pyfwsi) version: 20160106
[OK]            liblnk (pylnk) version: 20160107
[OK]            libmsiecf (pymsiecf) version: 20160107
[OK]            libolecf (pyolecf) version: 20160107
[FAILURE]       missing: pyqcow.
[OK]            libregf (pyregf) version: 20160107
[OK]            libsigscan (pysigscan) version: 20160108
[OK]            libsmdev (pysmdev) version: 20160108
[OK]            libsmraw (pysmraw) version: 20160108
[OK]            libvhdi (pyvhdi) version: 20160108
[FAILURE]       missing: pyvmdk.
[OK]            libvshadow (pyvshadow) version: 20160108
```

**Comment by joachimmetz** [comment]
1. This is plaso related, please file future issues [here](https://github.com/log2timeline/plaso/issues)
2. per: https://github.com/log2timeline/plaso/wiki/Troubleshooting#quick-list can you provide me with the relevant information, without it I can only guess what goes wrong. E.g. can you outline step by step how you install libvmdk and Python bindings

**Comment by dfirence** [comment]
Hi,

I have installed from source with the GIT  Project libraries for each.  After running the ./SYNCLIBS.SH and ./AUTOGEN.SH scripts, I  ran ./CONFIGURE --ENABLE-PYTHON --WITH-PREFIX.  Upon completion, I ran:  MAKE, MAKE CHECK, MAKE INSTALL, LDCONFIG.  I have both Python 2X and 3X.  However, my default Python shell is 2.7.11.


I reinstalled everything from scratch today, and LIBEWF is the only package not being seen. see below:

[OK]            artifacts version: 20150409
[OK]            bencode
[OK]            binplist version: 0.1.4
[OK]            construct version: 2.5.2
[OK]            dateutil version: 2.4.2
[OK]            dfvfs version: 20151231
[OK]            dpkt version: 1.8
[OK]            google.protobuf
[OK]            hachoir_core version: 1.3.3
[OK]            hachoir_parser version: 1.3.4
[OK]            hachoir_metadata version: 1.3.3
[OK]            IPython version: 4.0.0
[OK]            pefile version: 1.2.10-139
[OK]            psutil version: 3.3.0
[OK]            pyparsing version: 2.0.7
[OK]            pytz
[OK]            requests version: 2.9.1
[OK]            six version: 1.10.0
[OK]            sqlite3 version: 3.9.2
[OK]            yaml version: 3.11
[OK]            SleuthKit version: 4.2.0
[OK]            pytsk3 version: 20150406
[OK]            libbde (pybde) version: 20160108
[OK]            libesedb (pyesedb) version: 20160107
[OK]            libevt (pyevt) version: 20160107
[OK]            libevtx (pyevtx) version: 20160107
[FAILURE]       missing: pyewf.
[OK]            libfwsi (pyfwsi) version: 20160106
[OK]            liblnk (pylnk) version: 20160107
[OK]            libmsiecf (pymsiecf) version: 20160107
[OK]            libolecf (pyolecf) version: 20160107
[OK]            libqcow (pyqcow) version: 20160108
[OK]            libregf (pyregf) version: 20160107
[OK]            libsigscan (pysigscan) version: 20160108
[OK]            libsmdev (pysmdev) version: 20160108
[OK]            libsmraw (pysmraw) version: 20160108
[OK]            libvhdi (pyvhdi) version: 20160108
[OK]            libvmdk (pyvmdk) version: 20160108
[OK]            libvshadow (pyvshadow) version: 20160108

**Comment by dfirence** [comment]
At this time, I can run L2T but I believe I won't be able to parse EWF items.

**Comment by joachimmetz** [comment]
Are you running configure with:
```
./configure --enable-python --prefix=/usr
```

or just:
```
./configure --enable-python --prefix
```

You'll need the former. Also per https://github.com/log2timeline/plaso/wiki/Troubleshooting#import-errors did you try to analyze why the import of pyewf is failing?

**Comment by joachimmetz** [comment]
Marking as invalid since this question belongs on the plaso issue tracker.

**Comment by dfirence** [comment]
I will write you on GMAIL, no need to populate on GitHub as I do not feel there's an error.  Thank you for your assistance and prompt response.  TTY Soon :)
