### ISSUE TITLE
python binding for verify

### ISSUE THREAD

**Issue by finoradin** [libyal/libewf#34]
I see that it is possible through check_file_signature_file() to see if an EWF file has checksums, but as far as I can tell there is no function for actually validating the checksum. This would be great, as it appears that the checksum is not equivalent to a checksum of the whole EWF file itself, but of a specific subset of the file.

**Comment by joachimmetz** [comment]
To make sure I understand you correctly which "checksum" are you referring to?

* `check_file_signature_file` is intended to check the file signature (or magic type) of an individual EWF type.
* There are Adler-32 checksums in the sections and uncompressed data chunks.
* Ewfverify calculated a digest hash of the storage media data in a set of EWF files. 

Which are you referring to?

**Comment by joachimmetz** [comment]
No update from original reporter closing issue.

**Comment by finoradin** [comment]
I'm not sure which actually – my understanding is that if I have a EWF file, that the file contains a checksum of the contained data. Is there a way to validate this? I.e. with the CLI of FTKImager I can "validate" a disk image.

**Comment by joachimmetz** [comment]
Yes have a look at the ewfverify (it is similar to FTKImager validation). This is what it does in a nutshell:

* read and calculate the digest hash(es) of the data in the EWF file
* see if there are any read errors (based on the checksum and the compressed data)
* compare the digest hashes that are (optionally) stored in the file

Also see:

* help(pyewf_handle.pyewf_handle_get_hash_values)
* https://github.com/libyal/libewf/blob/master/documentation/Expert%20Witness%20Compression%20Format%20(EWF).asciidoc
* https://en.wikipedia.org/wiki/Checksum
* https://en.wikipedia.org/wiki/Cryptographic_hash_function

**Comment by finoradin** [comment]
Thanks!

Also, thanks for the wikipedia article about checksums :trollface:

**Comment by joachimmetz** [comment]
Noprob, I've added it largely for dis-ambiguity

**Comment by fabianlae** [comment]
Hi @joachimmetz,
I am trying to verify E01 images with Python (3.9.12) on a Windows machine (Windows 10 Pro 64bit). So like @finoradin I am looking for something like ewfverify on Linux that is applicable on a Windows machine. I can't find it in the libewf python binding. Only reading the stored verification hash works (pyewf_handle_get_hash_values), which however I have to compare with the calculated hash. Manually calculating the MD5 for an image file is proving to be very tricky and I haven't managed it yet.

Is there a known way to verify E01 images in Python (Windows)? Maybe even with the libewf Python binding?
Thanks in advance!

**Comment by joachimmetz** [comment]
@fabianlae why not compile ewfverify for Windows?
