### ISSUE TITLE
handle leak on libewf_handle_close() ( version libewf-20150126 )

### ISSUE THREAD

**Issue by azerg** [libyal/libewf#35]
**Brief:**
After creating E01 image with libewf, i'm executing following code:

```
if(libewf_handle_close(ewfHandle, NULL) == -1)
     std::cout << "Can't close EWF file handle";
if(libewf_handle_free(&ewfHandle, NULL) == -1)
     std::cout << "Can't free EWF file handle";
```

Before _libewf_handle_close_ i have, as expected, opened handle to %filename%.E01 file.
After execution of _libewf_handle_free_ this code i have opened handle to %filename%.E02 file.

**How i'm reproducing this:**
1. I'm creating image of disk that is **larger** than destination disk i'm writing image too.
2. In this case output is:
"Can't close EWF file handle"
"Can't free EWF file handle"
3. On executing _libewf_handle_close_ that is located inside _libewf_handle_free_ (libewf_handle.c) *.E02 file is being created and handle to that file remains opened.

**How i've fixed this**
As long as _libewf_handle_free_ calls _libewf_handle_close_, i left only call to _libewf_handle_free_ this fixed that trouble - *.e01 handle is being closed, no other files are created. Memory is freed.

**Trouble**
1. In your sample (ewfacquire.c:2928) you are calling:

```
if( imaging_handle_close(
         ewfacquire_imaging_handle,
         &error ) != 0 )
    {
        fprintf(
         stderr,
         "Unable to close output file(s).\n" );

        goto on_error;
    }
if( imaging_handle_free(
       &ewfacquire_imaging_handle,
       &error ) != 1 )
```

_imaging_handle_free_ after successfull call to _imaging_handle_close_. This might produce memory leak if _imaging_handle_close_ will fail.
-  If we call _handle_free_ _only_ after successful call to _handle_close_   -> it might produce memory leak
- If we call _handle_free_ _always_ after _handle_close_ -> this might produce handle leak (among with creating that *.e02 file)

**Comment by joachimmetz** [comment]
Thx for the report, I'll have a look as soon as time permits. Know that 20150126 is the experimental version, there is definitely work TBD on this.

**Comment by joachimmetz** [comment]
Tested with ewfacquire build from https://github.com/libyal/libewf/commit/7e67535057e9f5befd8322890fc155e0ca981e63 to write more data than space available.

```
Acquiry failed at: Nov 28, 2020 09:43:21
Unable to acquire input.
libewf_chunk_data_write: unable to write chunk data.
libewf_segment_file_write_chunk_data: unable to write chunk data.
libewf_write_io_handle_write_new_chunk_create_chunk: unable to write chunk data.
libewf_write_io_handle_write_new_chunk: unable to create chunk: 42791 in segment file: 1.
libewf_internal_handle_write_buffer_to_file_io_pool: unable to write new chunk.
libewf_handle_write_buffer: unable to write buffer.
storage_media_buffer_write_to_handle: unable to write storage media buffer.
imaging_handle_write_buffer: unable to write storage media buffer.
ewfacquire_read_input: unable to write storage media buffer.
Unable to close output file(s).
libcfile_file_write_buffer_with_error_code: unable to write to file with error: No space left on device
libcfile_file_write_buffer: unable to write to file.
libbfio_file_write_buffer: unable to write to file: test2.E01.
libbfio_internal_handle_write_buffer: unable to write to handle.
libbfio_handle_write_buffer: unable to write to handle.
libbfio_pool_write_buffer: unable to write to entry: 0.
libewf_chunk_data_write: unable to write chunk data.
libewf_segment_file_write_chunk_data: unable to write chunk data.
libewf_write_io_handle_write_new_chunk_create_chunk: unable to write chunk data.
libewf_write_io_handle_write_new_chunk: unable to create chunk: 42791 in segment file: 1.
libewf_internal_handle_write_finalize_file_io_pool: unable to write new chunk.
libewf_handle_close: unable to finalize write.
imaging_handle_close: unable to close output handle.
==838260== 
==838260== HEAP SUMMARY:
==838260==     in use at exit: 0 bytes in 0 blocks
==838260==   total heap usage: 259,833 allocs, 259,833 frees, 1,871,298,489 bytes allocated
==838260== 
==838260== All heap blocks were freed -- no leaks are possible
==838260== 
==838260== For lists of detected and suppressed errors, rerun with: -s
==838260== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Since no leaks were detected, closing issue. Reopen if issue still persists.

**Comment by joachimmetz** [comment]
Made some additional changes in the legacy version related to this issue https://github.com/libyal/libewf-legacy/commit/2ed2c9aa7d700327b648bb7930bce99a1a9ff66d
