### ISSUE TITLE
Tests don't run if the build directory contains the version number.

### ISSUE THREAD

**Issue by hillu** [libyal/libewf#39]
For building the Debian package using sbuild, I patched tests/test_*.sh so that they could be successfully run in a build directory `.../libewf-20160325`:

    -TEST_PREFIX=`basename ${TEST_PREFIX} | sed 's/^lib//'`;
    +TEST_PREFIX=`basename ${TEST_PREFIX} | sed 's/^lib//' | sed 's/-201.*$//'`;

(This change was also necessary for the recent `libsigscan` release.)
Wouldn't it be better to just hard-code `TEXT_PREFIX`?

**Comment by joachimmetz** [comment]
Why do you need to run the test for packaging? Most of them rely on test files that are not provided?

**Comment by joachimmetz** [comment]
Also you are packaging an **experimental** version that requires more work?

**Comment by hillu** [comment]
I don't **need** to run any tests, but I think in general it is a good idea to at least have some basic functionality tested that does not need extra data.

Do you think that Debian should not ship your software that is marked as experimental?

**Comment by joachimmetz** [comment]
> Do you think that Debian should not ship your software that is marked as experimental?

For the libewf experimental at the moment I would say yes. I rather have that you deploy the previous stable. I hope to get an alpha out soon. Could a README.packagers or equivalent help to clarify the state of a project?

> I think in general it is a good idea to at least have some basic functionality tested that does not need extra data.

Agree and this is work in progress, but portability is a challenge here and I cannot say I'm too enthusiastic about the existing test frameworks out there.

**Comment by hillu** [comment]
When I look at "Releases" here on github, I don't see a libewf with "stable" in its name. The same goes for many of the other projects.

When I started putting plaso and all its dependencies into Debian last year, I did wonder about "experimental" or "alpha" names as part of the file names, but didn't really put too much thought into it.

**Comment by joachimmetz** [comment]
>  I did wonder about "experimental" or "alpha" names as part of the file names

FYI: https://github.com/libyal/libyal/wiki

> When I look at "Releases" here on github, I don't see a libewf with "stable" in its name. 

The "stable" predates github it can be found here: https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/

> The same goes for many of the other projects.

Regarding other projects there are no "stable" versions yet. So there is only 1 version.

**Comment by joachimmetz** [comment]
Closing issue, test scripts have changed in the mean time.

**Comment by hillu** [comment]
The test scripts are still not quite right. With the change below, I am able to run them from a directory named like `libfooar-20160123`:
<pre>
-TEST_PREFIX=`basename ${TEST_PREFIX} | sed 's/^lib\([^-]*\)/\1/'`;
+TEST_PREFIX=`basename ${TEST_PREFIX} | sed 's/^lib\([^-]*\).*$/\1/'`;
</pre>

**Comment by joachimmetz** [comment]
Ack, I'll see if I can integrate your proposed changes, know that the test scripts will undergo more changes in the near future.
