### ISSUE TITLE
libewf: complete EWF2-Ex01 and EWF2-Lx01 read support

### ISSUE THREAD

**Issue by joachimmetz** [libyal/libewf#4]
* complete EWF2-Ex01 and EWF2-Lx01 read support

**Comment by uckelman** [comment]
What's the state of this? I might be interested in finishing the implementation for Ex01.

I had a look yesterday at your format description document and Guidance's spec, along side a compressed Ex01. I carved out the sector data, in which `bzip2recover` finds many, many compressed chunks. That seems like good news for being able to read the sector data.

Where I ran into difficulties is with the data for the device section. Guidance's spec says that this data is compressed, but not how; your document says that it's compressed using the compression method specified in the file header. When I looked at it in a hex editor, I saw that there's no bzip2 magic number at the start (nor is there one for gzip)---which is what `BZ2_bzBuffToBuffDecompress` complains about if you try to run `ewfinfo` on my test Ex01. Do you have any idea how this data is compressed?

**Comment by joachimmetz** [comment]
> What's the state of this?

Status is, continue working on this when time permits.

According to Guidance document, bzip2 compressed data in Ex01 is not the same as the bzip2 standard. Last time I looked EnCase did not support bzip2 yet. If you have a test file you can share e.g. of a small empty USB, volume I can take a closer look.

**Comment by uckelman** [comment]
> According to Guidance document, bzip2 compressed data in Ex01 is not the same as the bzip2 
standard. 

Which document is this?

**Comment by joachimmetz** [comment]
"EnCase Evidence File Format Version 2", version January 2012, by Guidance

**Comment by uckelman** [comment]
That's the one I have. Where does it say that the bzip2-compressed data doesn't follow the standard?

**Comment by joachimmetz** [comment]
Let me dig up my notes; I recall that the alignment of some bitstream members was different (https://en.wikipedia.org/wiki/Bzip2). Hence I need a sample to confirm if its a bug in the documentation or a different variation.

**Comment by uckelman** [comment]
Thanks. I'll see about getting you a test file.

**Comment by joachimmetz** [comment]
I've started migrating the documentation to asciidocs, here are the bzip2 notes:
https://github.com/libyal/libewf/blob/master/documentation/Expert%20Witness%20Compression%20Format%202%20(EWF2).asciidoc#51-bzip2-compression

**Comment by joachimmetz** [comment]
Moved bzip2 support to separate issue: https://github.com/libyal/libewf/issues/40

Working on resolving issue with read in separate issue: https://github.com/libyal/libewf/issues/38

Nothing left to do for this issue, closing.
