### ISSUE TITLE
pyewf

### ISSUE THREAD

**Issue by zhjun2512** [libyal/libewf#44]
import pyewf
file_object = open("image.E01", "wb")

ewf_handle = pyewf.handle()

ewf_handle.open_file_objects([file_object])
ewf_handle.write("dddddd")

ewf_handle.close()

IOError: pyewf_handle_write_offset: unable to write offset. libewf_handle_write_offset: invalid handle - missing file IO pool

why?

**Comment by joachimmetz** [comment]
Because you open the handle in read-only mode.

**Comment by zhjun2512** [comment]
I have modified this mistake, but still does not work

**Comment by joachimmetz** [comment]
could be that it is still work in progress - which version of libewf/pyewf?

**Comment by zhjun2512** [comment]
python 2.7

**Comment by joachimmetz** [comment]
That does not answer my question

**Comment by zhjun2512** [comment]
I'm sorry, my English is not very well, libewf_python-20160424.egg-info

**Comment by joachimmetz** [comment]
This is an experimental version of libewf, work in progress.
I'll have a look, as soon as time permits, if I can reproduce the issue.

**Comment by zhjun2512** [comment]
Thank you
