### ISSUE TITLE
ewfacquire error failure

### ISSUE THREAD

**Issue by serius777** [libyal/libewf#47]
I am trying to acquiring 8GB USB, and i always got error failure between 90%.
here error output

> Acquiry failed at: May 25, 2016 20:17:40
> Unable to acquire input.
> libcfile_file_read_buffer_with_error_code: invalid read count: 28672 returned.
> libsmdev_handle_read_buffer: unable to read from device file.
> device_handle_read_storage_media_buffer: unable to read buffer from device input handle.
> ewfacquire_read_input: error reading data from input.
> ewfacquire: FAILURE

what cause this error?

**Comment by joachimmetz** [comment]
* Which version of libewf?
* what is the command you are using?

**Comment by serius777** [comment]
hi joachimmetz, thank you for replay my question.
i run ewfacquire command from libewf-experimental-20160424 version in windows 7 64-bit.

> PS D:\cpro> ewfacquire.exe \\.\f:
> ewfacquire 20160424
> 
> Device information:
> Bus type:                               USB
> Vendor:                                 Kingston
> Model:                                  DataTraveler 2.0
> Serial:
> 
> Storage media information:
> Type:                                   Device
> Media type:                             Removable
> Media size:                             7,7 GB (7746349056 bytes)
> Bytes per sector:                       512
> 
> Acquiry parameters required, please provide the necessary input
> Image path and filename without extension: usb8gb
> Case number: 1
> Description: trying
> Evidence number: 1
> Examiner name: huda
> Notes: justtry
> Media type (fixed, removable, optical, memory) [removable]:
> Media characteristics (logical, physical) [logical]: physical
> Use EWF file format (ewf, smart, ftk, encase1, encase2, encase3, encase4, encase5, encase6, encase7, encase7-v2, linen5,
>  linen6, linen7, ewfx) [encase6]:
> Compression method (deflate) [deflate]:
> Compression level (none, empty-block, fast, best) [none]:
> Start to acquire at offset (0 <= value <= 7746349056) [0]:
> The number of bytes to acquire (0 <= value <= 7746349056) [7746349056]:
> Evidence segment file size in bytes (1,0 MiB <= value <= 7,9 EiB) [1,4 GiB]: 8,5 GiB
> The number of bytes per sector (1 <= value <= 4294967295) [512]:
> The number of sectors to read at once (16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768) [64]:
> The number of sectors to be used as error granularity (1 <= value <= 64) [64]:
> The number of retries when a read error occurs (0 <= value <= 255) [2]:
> Wipe sectors on read error (mimic EnCase like behavior) (yes, no) [no]:
> 
> The following acquiry parameters were provided:
> Image path and filename:                usb8gb.E01
> Case number:                            1
> Description:                            trying
> Evidence number:                        1
> Examiner name:                          huda
> Notes:                                  justtry
> Media type:                             removable disk
> Is physical:                            yes
> EWF file format:                        EnCase 6 (.E01)
> Compression method:                     deflate
> Compression level:                      none
> Acquiry start offset:                   0
> Number of bytes to acquire:             7,2 GiB (7746349056 bytes)
> Evidence segment file size:             8,5 GiB (9114222592 bytes)
> Bytes per sector:                       512
> Block size:                             64 sectors
> Error granularity:                      64 sectors
> Retries on read error:                  2
> Zero sectors on read error:             no
> 
> Continue acquiry with these values (yes, no) [yes]:

That is command i use. The `invalid read count` number in error message is not same for efery time i am tryng to acquire the USB. What is the meaning of value?

**Comment by joachimmetz** [comment]
Will have a look as soon as time permits.

**Comment by joachimmetz** [comment]
Closing issue as part of testing experimental version of the libary
