### ISSUE TITLE
flex.exe not responding when running configure

### ISSUE THREAD

**Issue by afik** [libyal/libewf#49]
Hi, i need help on building libewf latest release using MSYS-MinGW on Windows 10. When i run `CPPFLAGS=-DWINVER=0x0501 ./configure --prefix=/mingw` it keep stopping at flex checking and said flex.exe not responding. Do you have any idea on what should i do? Thanks.

**Comment by joachimmetz** [comment]
> Do you have any idea on what should i do?

Sounds to me like a MSYS-MinGW tool chain issue.
Check if the MSYS-MinGW flex version is recent
Try to determine what flex is doing, verbose output.

**Comment by afik** [comment]
I guess my MSYS-MinGW configuration wasn't correct, the stackdump pointing to flex.exe in GitHub. 
I try build using Cygwin but it gives me a lot of warning about `inline function declared but never defined` in libuna. And then `undefined referenced error` when those function being called. 
Do you have any idea what did i do wrong this time?

**Comment by joachimmetz** [comment]
Sounds like an older issue with how GCC interprets `inline`. https://github.com/libyal/libuna/issues/2
