### ISSUE TITLE
libewf fails to build - undefined reference to libcsystem_file_io_write

### ISSUE THREAD

**Issue by xambroz** [libyal/libewf#52]
Hello,
the build of libewf (version 20160519, commit 62ba5f578c9ffb0c651b82e06bb99a54a8f07af0) fails with following error:

gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall -c -o storage_media_buffer_queue.o storage_media_buffer_queue.c
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o ewfacquire byte_size_string.o digest_hash.o device_handle.o ewfacquire.o ewfinput.o ewfoutput.o guid.o imaging_handle.o log_handle.o platform.o process_status.o storage_media_buffer.o storage_media_buffer_queue.o -lodraw -lsmdev -lsmraw -luuid -lhmac -lfvalue -lfguid -lfdata -lcsystem -lbfio -lcpath -lcfile -luna -lcsplit -lcnotify -lclocale -lcdatetime -lcdata ../libewf/libewf.la -lcthreads -lcerror -lcstring

/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o ewfexport byte_size_string.o digest_hash.o ewfexport.o ewfinput.o ewfoutput.o export_handle.o guid.o log_handle.o platform.o process_status.o storage_media_buffer.o storage_media_buffer_queue.o -lsmraw -luuid -lhmac -lfvalue -lfguid -lfdata -lcsystem -lbfio -lcpath -lcfile -luna -lcsplit -lcnotify -lclocale -lcdatetime -lcdata ../libewf/libewf.la -lcthreads -lcerror -lcstring  
ewfacquirestream.o: In function `ewfacquirestream_read_chunk':
/home/mambroz/rpmbuild/BUILD/libewf-62ba5f578c9ffb0c651b82e06bb99a54a8f07af0/ewftools/ewfacquirestream.c:344: undefined reference to`libcsystem_file_io_read'
collect2: error: ld returned 1 exit status
Makefile:1199: recipe for target 'ewfacquirestream' failed
make[1]: **\* [ewfacquirestream] Error 1
make[1]: **\* Waiting for unfinished jobs....

libtool: link: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o .libs/ewfexport byte_size_string.o digest_hash.o ewfexport.o ewfinput.o ewfoutput.o export_handle.o guid.o log_handle.o platform.o process_status.o storage_media_buffer.o storage_media_buffer_queue.o  -lsmraw -luuid -lcsystem -lcdatetime ../libewf/.libs/libewf.so -L/usr/lib64 -lcdata -lclocale -lcnotify -lcsplit -luna -lcfile -lcpath -lbfio -lfcache -lfdata -lfguid -lfvalue -lz -lbz2 -lhmac -lcaes -lcthreads -lcerror -lcstring
export_handle.o: In function `export_handle_write_storage_media_buffer':
/home/mambroz/rpmbuild/BUILD/libewf-62ba5f578c9ffb0c651b82e06bb99a54a8f07af0/ewftools/export_handle.c:1148: undefined reference to`libcsystem_file_io_write'
collect2: error: ld returned 1 exit status
Makefile:1207: recipe for target 'ewfexport' failed

It seems that for some reason the macrose "libcsystem_file_io_read' and 'libcsystem_file_io_write' are not defined in the "libcsystem.h"  /-lcsystem.

Best regards
Michal Ambroz

**Comment by joachimmetz** [comment]
Why do you want to use libcsystem as a shared library?

**Comment by xambroz** [comment]
>Why do you want to use libcsystem as a shared library?

Except of being masochist ;) it is about the Fedora Packaging guidelines which require libraries to be compiled as share libraries rather than embedded code if it is possible. 
https://fedoraproject.org/wiki/Packaging:Guidelines#Shared_Libraries

**Comment by xambroz** [comment]
Seems that fuctions macros libcsystem_file_io_read and libcsystem_file_io_write used in the libewf are not part of the interface in the libcsystem/include/libcsystem.h resp. libcsystem.h.in 

Full build logs here:
https://copr.fedorainfracloud.org/coprs/rebus/infosec-rebus/build/437775/
https://copr-be.cloud.fedoraproject.org/results/rebus/infosec-rebus/fedora-23-x86_64/00437775-libewf/build.log.gz

Best regards
Michal Ambroz

**Comment by joachimmetz** [comment]
>  it is about the Fedora Packaging guidelines which require libraries to be compiled as share libraries rather than embedded code if it is possible. 

Regarding packaging:

* know that this version of libewf is **experimental** and you are trying to package "bleeding edge" I opt to stick with releases
* this depends what you define as a "shared library" I largely use libcsystem as a sub project not so much as an .so file.

**Comment by joachimmetz** [comment]
> But if you already treat it as a separate library with builds, check, library status it would be pitty to not compile it as shared library and instead to include it statically in all the dependencies on the way.

Largely for testing and code reuse, at the moment. Long term, not sure about having libcstring and libcsystem as separate libs.

**Comment by joachimmetz** [comment]
dependency on libcsystem removed.
