### ISSUE TITLE
libewf fails to build - HAVE_WINCRYPT

### ISSUE THREAD

**Issue by xambroz** [libyal/libewf#53]
Hello,
the build of libewf (version 20160802 commit 986cfbe60b306778e8fbe93e4864c628871659a8) fails to build on linux with following error:

checking varargs.h usability... no
checking varargs.h presence... no
checking for varargs.h... no
checking that generated files are newer than configure... done
configure: error: conditional "HAVE_WINCRYPT" was never defined.
Usually this means the macro was only invoked conditionally.
error: Bad exit status from /var/tmp/rpm-tmp.oIEWyJ (%build)

Best regards
Michal Ambroz

**Comment by joachimmetz** [comment]
Did you run `./autogen.sh` after updating from git?

**Comment by joachimmetz** [comment]
Are you using an shared version of libhmac?

**Comment by joachimmetz** [comment]
Made some tweaks when using a shared version of libhmac.

**Comment by xambroz** [comment]
>Did you run ./autogen.sh after updating from git?
yes I do.

>Are you using an shared version of libhmac?
yes I do.

>Made some tweaks when using a shared version of libhmac.
I will test.
