### ISSUE TITLE
ewfacquire - decrypted destination drive freeze/crash  (libewf-20140608)

### ISSUE THREAD

**Issue by aisuremm** [libyal/libewf#54]
ewfacquire **works** perfectly on a unencrypted destination drive, but crashes after a few seconds when the destination drive (decrypted and mounted to /mnt/temp) is used.

In other words, during acquisition the OS crashes somewhere around 1~15%. 

example: ewfacquire -t /mnt/temp /dev/sdc
works perfectly on an unencrypted drive but the exact same command fails/freezes if temp is a decrypted drive. 

Any reason why a mounted and decrypted drive crashes ewfacquire?

**Comment by joachimmetz** [comment]
Can you provide me with more details:

* which OS, any crash dumps, debug information, relevant system log entries?
* which version of libewf? how was it compiled?
* which ewfacquire options?
* how is the drive attached to the system?

**Comment by joachimmetz** [comment]
No input from original reporter. Closing issue as part of testing experimental version of the library #38
