### ISSUE TITLE
Provide Stream

### ISSUE THREAD

**Issue by florianbuehlmann** [libyal/libewf#55]
It would be great if the library would expose a System.IO.Stream so we don't need an extra wrapper class for providing stream access.

Or what would be the downside of having one?

**Comment by joachimmetz** [comment]
I assume you mean dot Net System.IO.Stream? The library is written in C and should work cross platform so adding a platform specific solution is not feasible. 

Unless you mean the ewf.net binding with "the library" feel free to contribute it. Know that this has a very low priority for me.

**Comment by florianbuehlmann** [comment]
Yes you are right, I meant the .NET System.IO.Stream.
OK, I will see if i can propose a solution the next days.

**Comment by florianbuehlmann** [comment]
Closing this issue, as I have realized:

1) The interest in having the stream is low
2) It can be done in a reasonable amount of time
