### ISSUE TITLE
No subsystem to mount EWF format

### ISSUE THREAD

**Issue by tedsmith** [libyal/libewf#56]
Joachim

Sorry to bother you. My colleagues and I are trying to mount a700Gb E01 image of a 3Tb disk on an Apple Mac Pro. We have installed libewf and Fuse of OSX and using the following mount syntax : 

> sudo ewfmount /Volumes/MyImage.E01 MyMountPoint 

After about a minute I get the error "No subsystem to mount EWF format". 

We have tried re-imaging the image as 1,5Gb segments and 4Gb segments. With 1500 segments there are too many E01 files (530 or so) and as 4Gb segments, we get the error. 

Hoping you can at least explain what triggers that error which may give us a clue as to what we are missing. Thanks Joachim

**Comment by joachimmetz** [comment]
You did not build with either fuse or dokan support

**Comment by tedsmith** [comment]
Ah, OK. Could you point me in the direction of a help page for that step so I can re-do it?

**Comment by joachimmetz** [comment]
Install fuse-dev or equiv and rerun configure, make, etc.
