### ISSUE TITLE
Cann't get device or media size and byte per sector

### ISSUE THREAD

**Issue by serius777** [libyal/libewf#57]
Hi  joachimmetz.
I don't know why this happen. Every time I run **ewfacquire** to partition or drive, it's always cann't get media size and byte per sector of input partition or drive.

> $ ewftools/ewfacquire \\.\c:
> ewfacquire 20160424
> 
> Device information:
> Bus type:
> Vendor:                                 TOSHIBisueA
> Model:                                  MK5076GSX
> Serial:                                 X17AC3EKT
> 
> Storage media information:
> Type:                                   Device
> Media type:                             Fixed
> Media size:                             N/A
> Bytes per sector:                       N/A

I try to recompile from source code, but still get same result. Do you know how to solve this problem?

**Comment by joachimmetz** [comment]
> Do you know how to solve this problem?

Yes this is actually handled by libsmdev. So `\\.\c:` is a virtual device, what if you use `\\.\PhysicalDrive0` ?

**Comment by serius777** [comment]
Hi joachimmetz.

I was try your advice, but the problem is still occur. 
I was try via command prompt, Power shell, and Msys console.

I didn't meet this problem before. I remember about 3 months ago, that my first time success compile libewf. **ewfacquire** can retrive `Media type`  and  `Media size` value from partition (`\\.\c:`, `\\.\d`, etc) or physical drive (`\\.\PhysicalDrive0`, `\\.\PhysicalDrive1`, etc).

Now I don't know what things(s) that make this problem occurs. I was try to reinstall Mingw and msys, but still not solve the problem.

**Comment by joachimmetz** [comment]
So libsmdev uses system API and IOCTL request to get the data you could compile libsmdev and smdevinfo with [Verbose and Debug output](https://github.com/libyal/libsmdev/wiki/Troubleshooting#verbose-and-debug-output), run that on the device and send me that log. That might indicate what is different in this case. Note that sometimes the device itself does not return the information or it requires a different system API call.

**Comment by serius777** [comment]
Hi joachimmetz.

I got error while compiling **libsmdev** and **smdevinfo**.

Here is my `./configure` script
`CPPFLAGS=-DWINVER=0x0501 ./configure --prefix=/mingw --enable-winapi=yes --enable-verbose-output --enable-debug-output`
After success configuring compilation, than i run `make`. 

here is error message i got.
> libsmdev_handle.c: In function 'libsmdev_internal_handle_determine_media_informa
> tion':
> libsmdev_handle.c:2977:14: error: 'response_count' undeclared (first use in this
>  function)
>      (size_t) response_count,
>               ^
> libsmdev_handle.c:2977:14: note: each undeclared identifier is reported only onc
> e for each function it appears in
> make[1]: *** [libsmdev_handle.lo] Error 1
> make[1]: Leaving directory `/home/HUDA/libsmdev-20160320/libsmdev'
> make: *** [all-recursive] Error 1

**Comment by joachimmetz** [comment]
that seem to be a bug in the debug output try replacing `response_count` by `( (STORAGE_DESCRIPTOR_HEADER *) response )->Size`. I'll correct that in libsmdev.

**Comment by serius777** [comment]
Hi joachimmetz.

Thank you for your guide. Now **libsmdev** has success compiled. Here is debug message from **smdevinfo**.

> $ smdevtools/smdevinfo.exe \\\\.\\PhysicalDrive0 -v
> smdevinfo 20160320
> 
> libcfile_file_io_control_read_with_error_code: unable to IO control device with
> error: Incorrect function.
> 
> libcfile_file_get_size: unable to query device for: IOCTL_DISK_GET_LENGTH_INFO.
> libcfile_file_io_control_read_with_error_code: unable to IO control device with
> error: Incorrect function.
> 
> libsmdev_handle_get_bytes_per_sector: unable to query device for: IOCTL_DISK_GET
> _DRIVE_GEOMETRY_EX.
> Device information:
> 00000000: 28 00 00 00 48 01 00 00  00 00 00 01 28 00 00 00   (...H... ....(...
> 00000010: 31 00 00 00 42 00 00 00  47 00 00 00 0b 00 00 00   1...B... G.......
> 00000020: 00 00 00 00 00 00 00 00  54 4f 53 48 49 42 41 20   ........ TOSHIBA
> 00000030: 00 4d 4b 35 30 37 36 47  53 58 20 20 20 20 20 20   .MK5076G SX
> 00000040: 20 00 47 53 30 30 00 20  20 20 20 20 20 20 20 20    .GS00.
> 00000050: 20 20 58 31 37 41 43 33  45 4b 54 00 00 00 00 00     X17AC3 EKT.....
> 00000060: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000070: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000080: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000090: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 000000a0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 000000b0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 000000c0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 000000d0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 000000e0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 000000f0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000100: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000110: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000120: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000130: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
> 00000140: 00 00 00 00 00 00 00 00                            ........
> 
> Bus type:               SATA
>         bus type                : Unknown: 0x00
>         vendor                  : TOSHIBA
>         model                   : MK5076GSX
>         serial                  : X17AC3EKT
> 
> Storage media information:
>         media type              : Fixed
>         media size              : 0 B (0 bytes)
> libcfile_file_io_control_read_with_error_code: unable to IO control device with
> error: Incorrect function.
> 
> libsmdev_handle_get_bytes_per_sector: unable to query device for: IOCTL_DISK_GET
> _DRIVE_GEOMETRY_EX.

**Comment by serius777** [comment]
Is this problem has relation with Mingw tools version?
I was try to compile **libewf** in another PC. So I installed Mingw into the another PC, following your [instruction](https://github.com/libyal/libewf/wiki/Building#building-with-msys-mingw) to compile **Libewf** with mingw. And I got same problem too.

this is only my assumption. I will try to compile **libew** with another compiler with cygwin and microsoft visual studio.

Here is Mingw tools list and its version

> binutils		[2.25.1-1]
> mingw-runtime	[3.22.1]
> w32api			[3.18.1]
> libgmp			[5.1.2-1]
> libmpc			[1.0.2]
> libiconv		[1.14-3]
> pthreads		[3.9.1.-1]
> gettext			[0.18.3.2-2]
> libz			[1.2.8-1]
> gcc-core		[4.9.3-1]
> mingw32-make	[3.82.90-2-cvs-20120902]
> msys			[1.0.19-1]
> bzip2			[1.0.6-4]

**Comment by joachimmetz** [comment]
> Is this problem has relation with Mingw tools version?

No it's a platform specific issue as indicated by "libsmdev uses system API and IOCTL request to get the data"

**Comment by serius777** [comment]
Hi joachimmetz.

> No it's a platform specific issue as indicated by "libsmdev uses system API and IOCTL request to get the data"

Am I miss some scripts while configuring? Or should I specific its target build to x86_64 in configure command?

**Comment by joachimmetz** [comment]
@serius777 it is not clear to what you asking in the context of my comment. I'll close this issue since libsmdev has been updated in the mean time.
