### ISSUE TITLE
python3 library import error

### ISSUE THREAD

**Issue by slo-sleuth** [libyal/libewf#58]
libewf-python installed with pip3, python 3.5.2.  

Attempt to import with ipython3 on Ubuntu 16.04 (amd64):

```
In [1]: import pyewf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-950c0ecf3ac8> in <module>()
----> 1 import pyewf

ImportError: /usr/local/lib/python3.5/dist-packages/pyewf.cpython-35m-x86_64-linux-gnu.so: undefined symbol: BZ2_bzBuffToBuffCompress
```

On Mac OS X 10.11, import is successful, but segmentation fault on open method:

```
ln [1]: import pyewf

ln [2]: image = pyewf.open('image.E01', 'r')
segmentation fault: 11
```

I have patched libewf-20140608 installed on both systems for compatibility to Sleuthkit 4.3.0.

**Comment by joachimmetz** [comment]
I'll have a closer look as soon as time permits.

**Comment by joachimmetz** [comment]
Changes in: https://github.com/libyal/libewf/commit/a529ac5bdf957005f826a79bb252fa5cd9d5a4eb should fix this
