### ISSUE TITLE
Stable release URL returns 502

### ISSUE THREAD

**Issue by zmwangx** [libyal/libewf#60]
The stable release URL https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/, which is what we use at the Homebrew package manager ([link to package](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libewf.rb)) now returns HTTP 502.

Could you please tag the stable releases on GitHub and upload the tarballs, or maybe host at least the most recent stable release elsewhere? Thanks.

**Comment by joachimmetz** [comment]
I'll try to have a look later this week

**Comment by zmwangx** [comment]
Thanks.

**Comment by joachimmetz** [comment]
Sorry got a bit delayed. 

Moving legacy releases to: https://github.com/libyal/legacy/

**Comment by zmwangx** [comment]
Thanks!
