### ISSUE TITLE
Cannot compile TSK 4.3.0

### ISSUE THREAD

**Issue by nannib** [libyal/libewf#61]
I built Libewf from your github in Ubuntu 16.04 LTS, all worked fine, but if I try to compile TSK 4.3.0 (The SleuthKit) I get this error, (after 'make' command):

libtool: link: g++ -g -O2 -pthread -o img_cat img_cat.o  -L/usr/local/lib ../../tsk/.libs/libtsk.a /usr/local/lib/libewf.so -lbfio -lpthread /usr/local/lib/libafflib.so -lssl -lcrypto -lrt -lz -ldl -lstdc++ -pthread
../../tsk/.libs/libtsk.a(ewf.o): In function `ewf_image_read':
/home/caine/Downloads/sleuthkit-4.3.0/tsk/img/ewf.c:67: undefined reference to `libewf_handle_read_random'
collect2: error: ld returned 1 exit status
Makefile:411: recipe for target 'img_cat' failed
make[2]: *** [img_cat] Error 1
make[2]: Leaving directory '/home/caine/Downloads/sleuthkit-4.3.0/tools/imgtools'
Makefile:373: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/caine/Downloads/sleuthkit-4.3.0/tools'
Makefile:569: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

If I try to compile libewf-20140406, for trying the old stable release instead of the new github release, I get this error (after 'make' command ):
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libcstring -I../libcerror -I../libcdata -I../libclocale -I../libcnotify -I../libuna -I../libcfile -I../libcpath -I../libfcache -g -O2 -Wall -MT libmfdata_file.lo -MD -MP -MF .deps/libmfdata_file.Tpo -c libmfdata_file.c  -fPIC -DPIC -o .libs/libmfdata_file.o
In file included from libmfdata_file.h:29:0,
                 from libmfdata_file.c:27:
libmfdata_libbfio.h:49:2: error: #error Missing libbfio.h
 #error Missing libbfio.h
  ^
In file included from libmfdata_file.c:27:0:
libmfdata_file.h:102:6: error: unknown type name 'libbfio_pool_t'
      libbfio_pool_t *file_io_pool,
      ^
In file included from libmfdata_file.c:28:0:
libmfdata_file_list.h:71:9: error: unknown type name 'libbfio_pool_t'
         libbfio_pool_t *file_io_pool,
         ^
libmfdata_file_list.h:77:1: warning: no semicolon at end of struct or union
 };
 ^
libmfdata_file_list.h:92:13: error: unknown type name 'libbfio_pool_t'
             libbfio_pool_t *file_io_pool,
             ^
libmfdata_file_list.h:98:6: error: expected ';', ',' or ')' before 'uint8_t'
      uint8_t flags,
      ^
libmfdata_file_list.h:163:6: error: unknown type name 'libbfio_pool_t'
      libbfio_pool_t *file_io_pool,
      ^
libmfdata_file_list.h:173:6: error: unknown type name 'libbfio_pool_t'
      libbfio_pool_t *file_io_pool,
      ^
libmfdata_file.c:378:6: error: unknown type name 'libbfio_pool_t'
      libbfio_pool_t *file_io_pool,
      ^
Makefile:687: recipe for target 'libmfdata_file.lo' failed
make[1]: *** [libmfdata_file.lo] Error 1
make[1]: Leaving directory '/home/caine/Downloads/libewf-20140406/libmfdata'
Makefile:804: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

How can I compile libewf and TSK? I'm stuck!

**Comment by joachimmetz** [comment]
> undefined reference tolibewf_handle_read_random'

TSK does not support the experimental (github) version of libewf 

> #error Missing libbfio.h

do you have libbfio installed separately? what does config.log tell you?

> How can I compile libewf and TSK? I'm stuck!

you don't need ewf support in TSK using ewfmount is more efficient

**Comment by nannib** [comment]
Thank you I solved removing libewf2, ewftool, etc. from synaptic and I made a fresh installation of libewf-20140608 taken from here: https://github.com/BitCurator/bitcurator/tree/master/externals 
(thanks to Kam Woods and Joachim Metz) :-)

**Comment by joachimmetz** [comment]
FYI legacy release can now be found here as well https://github.com/libyal/legacy/tree/master/libewf
