### ISSUE TITLE
Google download link 502 error

### ISSUE THREAD

**Issue by SylvainCecchetto** [libyal/libewf#62]
Hi,

The Google download link seems to be dead, and the brew install libewf doesn't work.

Link : https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/

Thanks for your help !

**Comment by joachimmetz** [comment]
> The Google download link seems to be dead

I'll put the package somewhere else. Also see: https://github.com/libyal/libewf/issues/60

> and the brew install libewf doesn't work.

This I cannot help you with, brew is a separate project.
