### ISSUE TITLE
corruption scenario: Tableau TD3 EWF image set has DEFLATE block_size_copy of 0

### ISSUE THREAD

**Issue by msuhanov** [libyal/libewf#63]
Hello.

I have an image created with a Tableau TD3 device, where the block_size_copy field (see _libewf/libewf_deflate.c_) is null, and the block_size field (see the same file) contains a valid non-zero size. When trying to mount the image, the following check fails: https://github.com/libyal/libewf/blob/master/libewf/libewf_deflate.c#L1487. Relaxing that check allows libewf to mount the image (and there is no hash mismatch between an acquisition log and a raw image seen in the mount point), so I will propose the following change to the line #1487 in the _libewf/libewf_deflate.c_:
`if(( block_size != block_size_copy ) && ( block_size_copy != 0 ))`

Unfortunately, I can't share the image. And I can't create a new image with the same properties after the latest firmware update.

**Comment by joachimmetz** [comment]
Thanks for the report, I'll have a look as soon as time permits.

**Comment by joachimmetz** [comment]
The DEFLATE RFC (https://tools.ietf.org/html/rfc1951#section-3.2.4) is inconclusive if NLEN should be set, however the zlib source does seem to expect it https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/inflate.c#L890

**Comment by joachimmetz** [comment]
I'll add this as a corruption scenario to the documentation. Based on your indication that the updated firmware no longer has this issue I assume that Tableau identified the error and has addressed this.

**Comment by joachimmetz** [comment]
Added to documentation https://github.com/libyal/libewf/commit/f7abea25d102f3c6194fefb96d615a91b86c17a6. Closing issue, since root problem was resolved in Tableau implementation. Reopen if this is a wider scale issue with EWF implementations.
