### ISSUE TITLE
Previous stable releases download link no longer works

### ISSUE THREAD

**Issue by ant1** [libyal/libewf#64]
Previous stable releases download link no longer works ( https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/ )

**Comment by joachimmetz** [comment]
Moved to: https://github.com/libyal/legacy/

**Comment by ant1** [comment]
Thanks.
Which version of libewf do you recommend to Linux/BSD distributions package maintainers?
sleuthkit and bulk_extractor require a bit of patching to work with the experimental version  ( s/libewf_handle_get_header_value_case_number/libewf_handle_get_utf8_header_value_case_number/ ; s/libewf_handle_read_random/libewf_handle_read_buffer_at_offset/ )

**Comment by joachimmetz** [comment]
> Which version of libewf do you recommend to Linux/BSD distributions package maintainers?

Stable legacy.

**Comment by joachimmetz** [comment]
Updated README in https://github.com/libyal/libewf/commit/faabd9e5b4070510c0012906a41ad964a9e84f88
