### ISSUE TITLE
Multithread support in ewfacquire

### ISSUE THREAD

**Issue by claudiocordara** [libyal/libewf#65]
Hello.
Someone can give me more detail about multithreading support in ewfacquire ?
I have compiled and runned the latest version and this feature seems already enabled.
I can see creation and "feeding" of threads, but the execution seem don't use all the core
available.
At the time how the threads are used ? For what task ? The target is to have a real parallel execution of ewfacquire ?

Thank You in advance for any help
Best Regards
Claudio Cordara

**Comment by joachimmetz** [comment]
> Someone can give me more detail about multithreading support in ewfacquire ?

0. yes

> I have compiled and runned the latest version and this feature seems already enabled.

1. the latest version is experimental, and yes multi threading is now enabled by default if, and only if, available

> I can see creation and "feeding" of threads, but the execution seem don't use all the core
available.

2. `ewfacquire -h` would have told you
```
	-j:     the number of concurrent processing jobs (threads), where
	        a number of 0 represents single-threaded mode (default is 4
	        if multi-threaded mode is supported)
```

> At the time how the threads are used ? For what task ?

compression

> The target is to have a real parallel execution of ewfacquire ?

No idea what you are asking with this.

**Comment by joachimmetz** [comment]
No response from original reporter, closing issue
