### ISSUE TITLE
Failed to build - fatal error: narrow_string.h

### ISSUE THREAD

**Issue by dustyhorizon** [libyal/libewf#66]
Currently am receiving error libcerror_error.c:24:27: fatal error: narrow_string.h: No such file or directory.
Was able to build libewf from source about one week ago though.

Any advice?

**Comment by joachimmetz** [comment]
This is a known issue due to code migration. If you're expecting a stable build use use a packed version as described here: https://github.com/libyal/libewf/wiki/Building#read-first
