### ISSUE TITLE
Image File Incompatability

### ISSUE THREAD

**Issue by jamdunnDFW** [libyal/libewf#67]
Here's the scenario...

I made two images (one a piece) using libewf-experimental-20160424 & libewf-experimental-20160403. I was able to successfully mount both using ewfmount and the linux mount command. However - when I try to open either image in FTK Imager the program fails and says I'm using an invalid image format. 

I'm using the default settings (EnCase 6 format), zero-block compression, and 4096M chunks. Any idea what may be causing the issue?

**Comment by joachimmetz** [comment]
Please only use the experimental version for testing for now.
