### ISSUE TITLE
TypeError: argument 1 must be string, not pyewf.handle

### ISSUE THREAD

**Issue by dmbina** [libyal/libewf#68]
@joachimmetz I am working on an forensic project for my master thesis. It's about extracting files from a forensic image (.E01) using python. I found your repository on Github to perfectly do so. But when I run your code found on the Wiki/Development page using python 2.7.12, I got this TypeError message. 

![dfirwizard_typeerror](https://cloud.githubusercontent.com/assets/23559224/20440291/fd493f46-ad84-11e6-871e-960314808191.PNG)

What should I do to fix it ? I mean this code makes perfect sense unless pytsk3.Img_Info is a string and the function ewf_Img_Info cannot take a pyewf.handle parameter ?

**Comment by joachimmetz** [comment]
Which version of pytsk and which version of libewf/pyewf are you using?

**Comment by joachimmetz** [comment]
> It's about extracting files from a forensic image (.E01) using python. 

I opt to have a look at: https://github.com/log2timeline/dfvfs

**Comment by dmbina** [comment]
I am using these versions 
![lib_versions](https://cloud.githubusercontent.com/assets/23559224/20450184/06f97d42-adb4-11e6-917f-12fa7071f5c5.PNG)

**Comment by dmbina** [comment]
I am using these versions 
` pyewf.get_version()
u'20140608'
pytsk3.get_version()
u'20160721'`

**Comment by joachimmetz** [comment]
I can reproduce it when I change `__init__` to `_init_`. Check if something got reformatted when you copy ans pasted the code e.g. that the double underscores in init got formatted as a single one. 

Closing issue.

**Comment by dmbina** [comment]
It worked ! Thanks. But I ran into another error 
 
![tsk3_error](https://cloud.githubusercontent.com/assets/23559224/20467569/da64cd34-af4f-11e6-8ecb-d6416af11bc0.PNG)

**Comment by joachimmetz** [comment]
Cou are likely trying to open a partition table as a file system. Check https://github.com/py4n6/pytsk/wiki/Development#accessing-a-file-system

```
When you try to access a file system make sure that the image object (img) contains a file system. If not you can pass pytsk3.FS_Info a byte offset of where the volume containing the file system starts, e.g.
```

**Comment by dmbina** [comment]
I want to open a full disk image (.dd) created with ProDiscover and containing two files.

**Comment by joachimmetz** [comment]
Can you be more specific what you mean with "full disk image". What type of storage media? Which partitioning schema? What volume systems? What file systems?

As indicated have a look at dfvfs and the pytsk examples. You are trying to re-implement what is already there.

**Comment by dmbina** [comment]
This is what the partition table through the OS shows : 
![partition](https://cloud.githubusercontent.com/assets/23559224/20473920/4d5fb8e2-af89-11e6-9e8e-bbb1d1083f6b.PNG)

And I created an raw image (.dd) of the entire drive. I looked into the dfvfs and the pytsk examples. I tried to implement the code from the dfirwizard repository and used the image from this blog http://www.hecfblog.com/2016/04/daily-blog-373-automating-dfir-with.html. But I still ran into the same issue.

**Comment by joachimmetz** [comment]
Have a look at: https://github.com/py4n6/pytsk/wiki/Development#iterating-volumes

And/Or try passing the volume offset as described here: https://github.com/py4n6/pytsk/wiki/Development#accessing-a-file-system

**Comment by dmbina** [comment]
:( It still doesn't work...
![access_fs](https://cloud.githubusercontent.com/assets/23559224/20515103/946ba148-b055-11e6-99b8-82ddf86f1291.PNG)
 I even passed the volume offset as you suggested:
![fs_offset](https://cloud.githubusercontent.com/assets/23559224/20515121/ae639c7c-b055-11e6-8a1f-d10974e2070c.PNG)

**Comment by joachimmetz** [comment]
and did you confirm "2048 x 512" is the offset of the volume in your test image? or are you just blindly copy pasting example code?

**Comment by dmbina** [comment]
Sorry I sent you the wrong file:
![access_fs](https://cloud.githubusercontent.com/assets/23559224/20548260/8be22622-b0e7-11e6-8d41-3b8f5b560010.PNG)

this is the offset using wmic command

![wmic](https://cloud.githubusercontent.com/assets/23559224/20548443/21c5db4c-b0e9-11e6-9680-3d1797a6a727.PNG)

**Comment by joachimmetz** [comment]
And that is the same offset as in the `.dd` image ? what does the partition table in the image tell you?

**Comment by dmbina** [comment]
Sorry @joachimmetz, I didn't really have time to respond, its so intense now with my finals :-(.
I managed to get the Volume_Info code working: 
![pytsk3_volume_info](https://cloud.githubusercontent.com/assets/23559224/20993797/3ea48914-bcb2-11e6-8df6-c6f92ca7cf18.PNG)

But I still got stuck when I tried to access the file system:
![pytsk3_fs_info](https://cloud.githubusercontent.com/assets/23559224/20993817/5e7fcef6-bcb2-11e6-99df-a99319ec336d.PNG)

**Comment by joachimmetz** [comment]
what do the first 512 bytes at offset 1048576 look like as a hexdump?

**Comment by dmbina** [comment]
If this is what you meant:
![hexdump_usbimg](https://cloud.githubusercontent.com/assets/23559224/21022675/11d390ce-bd43-11e6-99f4-f454ea8f8955.PNG)

**Comment by dmbina** [comment]
Thanks so much, I fixed it with fsstat and file... I think so ;)
![dfirwizard_2](https://cloud.githubusercontent.com/assets/23559224/21031845/4e257e8e-bd6b-11e6-98d0-2afc65138f82.PNG)

But that's not really what I am trying to realize here. I created a raw image (usbimg3.dd) of a USB drive containing 2 files (.jpg and .doc). The goal here is to extract the meta data and header/footer of these 2 files from usbimg3.dd with python. 

Can you just point me out how to do it ?

**Comment by joachimmetz** [comment]
> If this is what you meant:

Yes, based on the data I would say you're volume offset is wrong

> Can you just point me out how to do it ?

Who is doing the master thesis here? Part of an MSc program is being able do research independently, so I'll reply with questions. What could you search for to answer your question? Any prior art (already mentioned) could you look at?
