### ISSUE TITLE
bzip2 support with mysys2

### ISSUE THREAD

**Issue by serius777** [libyal/libewf#70]
Hi, I was compiling libewf library using mysys2 (use mingw64). Configure process was detects that I have bzip2 library and development. But after compiling process done than i checked libewf-3.dll with Dependency Walker, i saw that my compiled libewf library not has dependen with libbz2-1.dll. And ewfacquire did not support bzip2 compression.

Here is my screenshot.
![nobzip2](https://cloud.githubusercontent.com/assets/19471244/21101801/dded873a-c0b5-11e6-9fe9-5c3ef1861f57.PNG)

Here is my configure command to build libewf using mysys2
`CPPFLAGS=-DWINVER=0x0501 ./configure --host=x86_64-w64-mingw32`

thanks.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libewf/issues/40
