### ISSUE TITLE
undefined reference to libuna when building

### ISSUE THREAD

**Issue by jalwood** [libyal/libewf#72]
Using legacy stable release libewf-20140608 when I use the make command I end up with undefined references to libuna (small sample below)

/bin/bash ../libtool --tag=CC   --mode=link gcc  -g -O2 -Wall   -o ewfacquire byte_size_string.o digest_hash.o device_handle.o ewfacquire.o ewfinput.o ewfoutput.o guid.o imaging_handle.o log_handle.o platform.o process_status.o storage_media_buffer.o ../libodraw/libodraw.la ../libsmdev/libsmdev.la ../libsmraw/libsmraw.la ../libhmac/libhmac.la -lcrypto -ldl ../libcsystem/libcsystem.la ../libcsplit/libcsplit.la ../libcdatetime/libcdatetime.la ../libewf/libewf.la ../libcnotify/libcnotify.la ../libclocale/libclocale.la ../libcerror/libcerror.la ../libcstring/libcstring.la  -lbz2 
libtool: link: gcc -g -O2 -Wall -o .libs/ewfacquire byte_size_string.o digest_hash.o device_handle.o ewfacquire.o ewfinput.o ewfoutput.o guid.o imaging_handle.o log_handle.o platform.o process_status.o storage_media_buffer.o  ../libodraw/.libs/libodraw.a ../libsmdev/.libs/libsmdev.a ../libsmraw/.libs/libsmraw.a ../libhmac/.libs/libhmac.a -lcrypto ../libcsystem/.libs/libcsystem.a ../libcsplit/.libs/libcsplit.a ../libcdatetime/.libs/libcdatetime.a ../libewf/.libs/libewf.so -L/usr/local/lib -lz -ldl -lpthread ../libcnotify/.libs/libcnotify.a ../libclocale/.libs/libclocale.a ../libcerror/.libs/libcerror.a ../libcstring/.libs/libcstring.a -lbz2
../libsmraw/.libs/libsmraw.a(libuna_byte_stream.o): In function `libuna_byte_stream_size_from_utf8':
/tools/libewf-20140608/libuna/libuna_byte_stream.c:84: undefined reference to `libuna_unicode_character_copy_from_utf8'
/tools/libewf-20140608/libuna/libuna_byte_stream.c:102: undefined reference to `libuna_unicode_character_size_to_byte_stream'
../libsmraw/.libs/libsmraw.a(libuna_byte_stream.o): In function `libuna_byte_stream_copy_from_utf8':
/tools/libewf-20140608/libuna/libuna_byte_stream.c:185: undefined reference to `libuna_unicode_character_copy_from_utf8'
/tools/libewf-20140608/libuna/libuna_byte_stream.c:203: undefined reference to `libuna_unicode_character_copy_to_byte_stream'
../libsmraw/.libs/libsmraw.a(libuna_byte_stream.o): In function `libuna_byte_stream_size_from_utf16':
/tools/libewf-20140608/libuna/libuna_byte_stream.c:277: undefined reference to `libuna_unicode_character_copy_from_utf16'
...
collect2: error: ld returned 1 exit status
Makefile:1015: recipe for target 'ewfacquire' failed
make[1]: *** [ewfacquire] Error 1
make[1]: Leaving directory '/tools/libewf-20140608/ewftools'
Makefile:781: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I've attached the text file with the entire log.  I'm using Kali Linux.  Thanks for any help you can offer.

[compiler.txt](https://github.com/libyal/libewf/files/669326/compiler.txt)

**Comment by joachimmetz** [comment]
This might be related to the usage of inline in libuna also see: https://github.com/libyal/libuna/issues/2

**Comment by jalwood** [comment]
Thank you for the quick response!  That link was perfect, building a stand alone libuna worked and libewf compiled properly
