### ISSUE TITLE
Creating a logical evidence file

### ISSUE THREAD

**Issue by odibrowne** [libyal/libewf#73]
Is it possible to create a logical evidence file with libewf. I am trying to get a subset of a files contained within a file system based on file extension, file signature or md5 that match certain criteria and create a logical evidence file of only those.

**Comment by joachimmetz** [comment]
If by "logical evidence file" you mean L01, then currently no. See: https://github.com/libyal/libewf/issues/6

but these are not much different from any archive file, were you store additional metadata

**Comment by joachimmetz** [comment]
No response from original reporter closing issue.
