### ISSUE TITLE
20160424 version much slower than older version

### ISSUE THREAD

**Issue by eklann** [libyal/libewf#74]
Hi,

I am using tsk together with libewf to read disk images, and I have previously used an old experimental version of libewf which has worked fine in most aspects.

I am now trying to use the latest released version of libewf with tsk. I have it working, after making a small change in the tsk code. It seems that a function in libewf earlier called libewf_handle_read_random is now called libewf_handle_read_buffer_at_offset instead, and that is what I changed in the tsk code.

The problem that I have is that something makes reading from EWF images very slow with the new libewf version. I have traced the bulk (close to 100%) of the time consumption to a function in libewf called libewf_segment_file_read_chunk_group_element_data. 

Reading e.g. a volume label, or files from the disk image are extremely slow (something around 20 times slower) compared to the older version that I have used. Is this a problem that you have seen before, or do you have any ideas about how to solve it?

**Comment by joachimmetz** [comment]
> Is this a problem that you have seen before, or do you have any ideas about how to solve it?

It could be related to the additional verification needed for because of lack of decent integrity check in the E01 format. A code profiling could help to determine where the issue resided.

**Comment by eklann** [comment]
If you mean something like CPU-sampling when you say code profiling, that is basically what I did to conclude that libewf_segment_file_read_chunk_group_element_data is taking up nearly all of the time.

For purposes of testing, is it possible to disable the additional verification that you mention?

**Comment by eklann** [comment]
Is it possible to disable the additional verification for purposes of testing?

**Comment by joachimmetz** [comment]
> Is it possible to disable the additional verification for purposes of testing?

Yes the source is open just look for adler32 in the library and comment it out
