### ISSUE TITLE
Downloads link in README giving 404

### ISSUE THREAD

**Issue by ajnelson-nist** [libyal/libewf#75]
The link as of [today's most recent commit](11a3f4767ae5a11bbacb04d42988819459750ad2) is inoperational.

**Comment by joachimmetz** [comment]
This was moved to: https://github.com/libyal/legacy/tree/master/libewf

Updated README in https://github.com/libyal/libewf/commit/faabd9e5b4070510c0012906a41ad964a9e84f88
