### ISSUE TITLE
How to use libewf to search and read files?

### ISSUE THREAD

**Issue by felixi1986** [libyal/libewf#78]
Hello everyone,
I want to use libewf to search the desired files in a EWF-image. But after some days working I still haven't get the solution about it. I didn't have so many experience with the EWF-image and this lib. Could anyone give some advice?

For example I want search if there some txt-Data in the image, what should I do? 

- Should I first mount the image file and then search and read? 

- Or can I do search and read without the mount?

thanks for any answer.

**Comment by joachimmetz** [comment]
EWF is a container format. Libewf does not handle interpreting the contents for you. You'll need other tools to do this.

**Comment by felixi1986** [comment]
Hello Joachimmetz,
thanks for your answer.
I must misunderstand the _**Read or write supported EWF**_ of the libewf. I thought that means it could read the data in the E01 files and show them just like the windows Explorer.

**Comment by tedsmith** [comment]
I implemented by buffer reads from the E01, as provided by the libewf.open 

https://github.com/tedsmith/yaffi/blob/master/UYaffi.pas#L2013
