### ISSUE TITLE
ewfacquire multi-threaded fails to stop on error

### ISSUE THREAD

**Issue by brucemarkey** [libyal/libewf#79]
When compiled with multi-threading and using more than one thread, ewfacquire does not stop on errors such as the source drive being removed or the target drive filling to capacity (i.e. read/write errors).  Using one thread, these situations are detected and handled as expected.

**Comment by joachimmetz** [comment]
Will have a look as soon as time permits, this version of libewf is considered experimental

**Comment by joachimmetz** [comment]
Some changes in https://github.com/libyal/libewf/commit/277e9ec047ee38eb6bbfe3f5bb067f4c4895c249

**Comment by joachimmetz** [comment]
Changes for drive being removed on Linux https://github.com/libyal/libsmdev/commit/a52f24f43609b336182dd9e8e886e017489b0ad7

**Comment by joachimmetz** [comment]
changes should address original issues, closing issue
