### ISSUE TITLE
fatal error: libsmraw_metadata.h: No such file or directory

### ISSUE THREAD

**Issue by jijames** [libyal/libewf#81]
Fresh install Ubuntu Linux running synclibs.sh, autogen.sh, configure, make results in the following error:

> ewftools_libsmraw.h:30:31: fatal error: libsmraw_metadata.h: No such file or directory

Solution:
Remove libsmraw dir, clone full source from git, build and install.
Re-run libewf autogen, configure, make, ldconfg

**Comment by joachimmetz** [comment]
Was fixed in https://github.com/libyal/libewf/commit/a08342a8979a454805160a8069ece4bc72834295
