### ISSUE TITLE
ewftools_find.h is missing in libewf-experimental-20170605.tar.gz

### ISSUE THREAD

**Issue by conraid** [libyal/libewf#82]
ewftools_find.h is missing in file libewf-experimental-20170605.tar.gz but in ewftools/ewftools_glob.c

```
#include <stdlib.h>
#endif

#if defined( HAVE_IO_H ) || defined( WINAPI )
#include <io.h>
#endif

#include "ewftools_find.h"
```

**Comment by joachimmetz** [comment]
thx for the report I'll have a look

**Comment by joachimmetz** [comment]
made some changes for deployment: https://github.com/libyal/libewf/commit/62d6526c96990646f6d256f7a51e60ab7dc03fa9

this should address the issue, please reopen if not

**Comment by joachimmetz** [comment]
Uploaded libewf-experimental-20170703
