### ISSUE TITLE
ewftools_find.h missing from source tarball 

### ISSUE THREAD

**Issue by gaelanadams** [libyal/libewf#83]
Hi, 

I downloaded 20170605 source and was trying to build it however I receive the following error:

> gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcerror -I../libcthreads -I../libcdata -I../libcdatetime -I../libclocale -I../libcnotify -I../libcsplit -I../libuna -I../libcfile -I../libcpath -I../libbfio -I../libfcache -I../libfdata -I../libfvalue -I../libhmac -I../libodraw -I../libsmdev -I../libsmraw -DLIBEWF_DLL_IMPORT -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64  -g -O2 -Wall -MT ewftools_glob.o -MD -MP -MF .deps/ewftools_glob.Tpo -c -o ewftools_glob.o ewftools_glob.c
ewftools_glob.c:41:27: fatal error: ewftools_find.h: No such file or directory
 #include "ewftools_find.h"
                           ^
compilation terminated.
Makefile:1263: recipe for target 'ewftools_glob.o' failed
make[1]: *** [ewftools_glob.o] Error 1
make[1]: Leaving directory '/home/gadams/Builds/libewf-20170605/ewftools'
Makefile:841: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

After I manually grabbed the ewftools_find.h and placed it in ewftools folder it proceeded 'make' correctly.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libewf/issues/82

**Comment by joachimmetz** [comment]
Will be fixed in next release

**Comment by joachimmetz** [comment]
Uploaded libewf-experimental-20170703
