### ISSUE TITLE
libewf-experimental-20170605.tar.gz build failure

### ISSUE THREAD

**Issue by fefe17** [libyal/libewf#84]
gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcerror -I../libcthreads -I../libcdata -I../libcdatetime -I../libclocale -I../libcnotify -I../libcsplit -I../libuna -I../libcfile -I../libcpath -I../libbfio -I../libfcache -I../libfdata -I../libfvalue -I../libhmac -I../libodraw -I../libsmdev -I../libsmraw -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -pipe -O2 -Wall -MT ewftools_glob.o -MD -MP -MF .deps/ewftools_glob.Tpo -c -o ewftools_glob.o ewftools_glob.c
ewftools_glob.c:41:10: fatal error: ewftools_find.h: No such file or directory
 #include "ewftools_find.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1263: ewftools_glob.o] Error 1
make[1]: Leaving directory '/tmp/libewf-20170605/ewftools'
make: *** [Makefile:841: all-recursive] Error 1

**Comment by joachimmetz** [comment]
Covered in https://github.com/libyal/libewf/issues/83

**Comment by joachimmetz** [comment]
uploaded libewf-experimental-20170703
