### ISSUE TITLE
ewfmount:Unable to run dokan main: unable to load driver

### ISSUE THREAD

**Issue by crazypenguincode** [libyal/libewf#86]
.\ewfmount.exe D:\win7.E01 x:
when  debug,the dokan debut-output is :"Dokan Error: CreatFile Failed \\.\Dokan: 2"
on win10 ,and the dokan from you git
do you have any suggestion

**Comment by joachimmetz** [comment]
Likely because the currently supported version of dokan is too old for Windows 10. Also see: https://github.com/libyal/libqcow/issues/5

**Comment by crazypenguincode** [comment]
thank you ,i have see when time permits,you will support latest dokany . **https://github.com/libyal/libqcow/issues/5**
