### ISSUE TITLE
Make Physical Disk E01 file

### ISSUE THREAD

**Issue by sspring** [libyal/libewf#91]
development environment:
1. OS:Windows 10
2. libewf version: 20171104

I get the following error when I try to open the output e01 file as a Disk using X-Ways Forensics.
![image](https://user-images.githubusercontent.com/7046668/33757816-ccd2c56c-dc36-11e7-8cb1-50add5e2be13.png)
I think there is something wrong with settings on libewf_handle.
BTW,Can ewf know it is a volume image or a disk image? and how can it get that?

**Comment by joachimmetz** [comment]
Likely related: https://github.com/libyal/libewf/issues/38, this version of libewf is still experimental for now use https://github.com/libyal/libewf-legacy instead

**Comment by joachimmetz** [comment]
> BTW,Can ewf know it is a volume image or a disk image? and how can it get that?

there is a flag in the metadata, however a forensic tool should not rely on this.

**Comment by sspring** [comment]
so is there a function in libewf or libewf-legacy that I can used to set this flag? and any documentation about this flag?

**Comment by joachimmetz** [comment]
> and any documentation about this flag?

https://github.com/libyal/libewf/blob/master/documentation/Expert%20Witness%20Compression%20Format%20(EWF).asciidoc#356-media-flags

**Comment by sspring** [comment]
Why can't I use libewf instead of libewf-legacy?There is a bug about this flag in libewf?(I'm using libewf  and It seems work well)

**Comment by joachimmetz** [comment]
You can use libewf if you want just know it is still experimental and not
production ready

**Comment by sspring** [comment]
thanks for your reminding. I will use libewf-legacy.
