### ISSUE TITLE
Build instructions for Microsoft Visual Studio are not viable

### ISSUE THREAD

**Issue by 0x736E** [libyal/libewf#92]
I tried following the build instructions for Windows but they are no longer viable. In particular the section regarding the Dokan library is out of date:
- Dokan library link is broken
- Dokan library subversion path does not exist
- Dokan library patchfile does not exist

The first two of these issues can be resolved by looking at https://github.com/dokan-dev/dokany/wiki/Build but the patchfile is missing, so I cannot go any further.

**Comment by joachimmetz** [comment]
A patched version of dokan can be found here: https://github.com/joachimmetz/dokan.git

but agree documentation could need some love and need to implement support for the new dokan as well

**Comment by joachimmetz** [comment]
support for DokanY was added to the experimental version in the mean time, closing issue.
