### ISSUE TITLE
unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by ridders** [libyal/libewf#97]
How do I resolve this error on Microsoft Windows 7? Would it be possible to have a wheel file for this library in the future to resolve this?

**Comment by joachimmetz** [comment]
> How do I resolve this error on Microsoft Windows 7?

Install Microsoft Visual C++ Compiler for Python 2.7
https://www.microsoft.com/en-us/download/details.aspx?id=44266

> Would it be possible to have a wheel file for this library in the future to resolve this?

Maybe. This is a very low priority on my list.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libyal/issues/68
