### ISSUE TITLE
How to open .E01 file for read and write together?

### ISSUE THREAD

**Issue by NimbleYurk** [libyal/libewf#99]
Hello!

I try to use function libewf_handle_open_wide() for read and write .E01 file.
If I use access flag LIBEWF_OPEN_READ all works cool.
But if I use access flag LIBEWF_OPEN_READ | LIBEWF_OPEN_WRITE or libewf_get_access_flags_read_write() I receave error: "libewf_handle_open_wide: unable to open handle using a file IO pool."

Part of my code:

	libewf_handle_t *hLibewfHandleRW = NULL;
	wchar_t** fileNames = nullptr;
	int numberOfFileNames = 0;
	libewf_error_t* error = nullptr;
	if (libewf_glob_wide(E01_FILE_NAME_READ_W, wcslen(E01_FILE_NAME_READ_W), LIBEWF_FORMAT_UNKNOWN, &fileNames, &numberOfFileNames, &error) != 1)
		return -1;

	int nRet = 0;
	if (libewf_handle_initialize(&hLibewfHandleRW, &error) != 1)
		return -1;
	if (hLibewfHandleRW == nullptr)
		return -2;

	nRet = libewf_handle_open_wide(hLibewfHandleRW, fileNames, numberOfFileNames, libewf_get_access_flags_read_write(), &error);

**Comment by joachimmetz** [comment]
Per https://github.com/libyal/libewf/issues/36 read write support will be removed from the library.

It makes more sense to have a stand-alone implementation that provides a read/write overlay on top of a raw data stream, such as the content of an EWF image set.
